const fs = require('fs');

const lines = [
"'use client'",
"import { useState, useEffect } from 'react'",
"import { createClient } from '../../../lib/supabase'",
"import { useRouter } from 'next/navigation'",
"",
"const DAYS = ['Mon','Tue','Wed','Thu','Fri','Sat','Sun']",
"const DAY_NUMS = [1,2,3,4,5,6,0] // JS getDay() mapping",
"const TIMES = ['Morning','Afternoon','Evening','Night']",
"const UNITS = ['mg','mcg','IU']",
"",
"type Compound = {",
"  name: string",
"  vial_strength: string",
"  vial_unit: string",
"  bac_water_ml: string",
"  reconstitution_date: string",
"  dose: string",
"  dose_unit: string",
"  duration_weeks: string",
"  days_of_week: number[]",
"  time_of_day: string",
"  vials_in_stock: string",
"  notes: string",
"}",
"",
"function newCompound(): Compound {",
"  return {",
"    name: '',",
"    vial_strength: '',",
"    vial_unit: 'mg',",
"    bac_water_ml: '',",
"    reconstitution_date: new Date().toISOString().split('T')[0],",
"    dose: '',",
"    dose_unit: 'IU',",
"    duration_weeks: '12',",
"    days_of_week: [],",
"    time_of_day: 'Morning',",
"    vials_in_stock: '',",
"    notes: '',",
"  }",
"}",
"",
"export default function ManagePage() {",
"  const router = useRouter()",
"  const [loading, setLoading] = useState(true)",
"  const [protocols, setProtocols] = useState<any[]>([])",
"  const [showForm, setShowForm] = useState(false)",
"  const [editingId, setEditingId] = useState<string | null>(null)",
"  const [startDate, setStartDate] = useState(new Date().toISOString().split('T')[0])",
"  const [compounds, setCompounds] = useState<Compound[]>([newCompound()])",
"  const [saving, setSaving] = useState(false)",
"  const [error, setError] = useState('')",
"",
"  const g = 'var(--color-green)', dg = 'var(--color-dim)', mg = 'var(--color-muted)'",
"  const cb = 'var(--color-card)', bd = 'var(--color-border)', inp = 'var(--color-input)'",
"",
"  useEffect(() => { load() }, [])",
"",
"  async function load() {",
"    setLoading(true)",
"    const supabase = createClient()",
"    const { data: { user } } = await supabase.auth.getUser()",
"    if (!user) { router.push('/auth/login'); return }",
"    const { data } = await supabase.from('protocols').select('*, compounds(*, phases(*))').order('created_at', { ascending: false })",
"    setProtocols(data || [])",
"    setLoading(false)",
"  }",
"",
"  function startNew() {",
"    setEditingId(null)",
"    setStartDate(new Date().toISOString().split('T')[0])",
"    setCompounds([newCompound()])",
"    setShowForm(true)",
"    setError('')",
"  }",
"",
"  function startEdit(p: any) {",
"    setEditingId(p.id)",
"    setStartDate(p.start_date)",
"    const cs = (p.compounds || []).map((c: any) => {",
"      const ph = (c.phases || [])[0]",
"      return {",
"        name: c.name,",
"        vial_strength: c.vial_strength?.toString() || '',",
"        vial_unit: c.vial_unit || 'mg',",
"        bac_water_ml: c.bac_water_ml?.toString() || '',",
"        reconstitution_date: c.reconstitution_date || new Date().toISOString().split('T')[0],",
"        dose: ph?.dose?.toString() || '',",
"        dose_unit: ph?.dose_unit || 'IU',",
"        duration_weeks: ph?.duration_weeks?.toString() || ph?.end_week?.toString() || '12',",
"        days_of_week: ph?.days_of_week || [],",
"        time_of_day: ph?.time_of_day || 'Morning',",
"        vials_in_stock: c.vials_in_stock?.toString() || '',",
"        notes: c.notes || '',",
"      }",
"    })",
"    setCompounds(cs.length ? cs : [newCompound()])",
"    setShowForm(true)",
"    setError('')",
"  }",
"",
"  function updateCompound(i: number, field: string, value: any) {",
"    const u = [...compounds]",
"    ;(u[i] as any)[field] = value",
"    setCompounds(u)",
"  }",
"",
"  function toggleDay(ci: number, dayNum: number) {",
"    const u = [...compounds]",
"    const days = u[ci].days_of_week",
"    u[ci].days_of_week = days.includes(dayNum) ? days.filter(d => d !== dayNum) : [...days, dayNum]",
"    setCompounds(u)",
"  }",
"",
"  async function save() {",
"    setError('')",
"    if (compounds.some(c => !c.name.trim())) { setError('Every compound needs a name.'); return }",
"    if (compounds.some(c => !c.dose.trim())) { setError('Every compound needs a dose.'); return }",
"    if (compounds.some(c => !c.reconstitution_date)) { setError('Reconstitution date is required.'); return }",
"    if (compounds.some(c => !c.bac_water_ml)) { setError('BAC water amount is required.'); return }",
"    if (compounds.some(c => c.days_of_week.length === 0)) { setError('Select at least one injection day.'); return }",
"    setSaving(true)",
"    const supabase = createClient()",
"    const { data: { user } } = await supabase.auth.getUser()",
"    if (!user) { setError('Not signed in.'); setSaving(false); return }",
"    const pName = compounds[0].name.trim()",
"    let protocolId = editingId",
"    if (editingId) {",
"      await supabase.from('protocols').update({ name: pName, start_date: startDate }).eq('id', editingId)",
"      await supabase.from('compounds').delete().eq('protocol_id', editingId)",
"    } else {",
"      const { data: p, error: e } = await supabase.from('protocols').insert({ user_id: user.id, name: pName, start_date: startDate }).select().single()",
"      if (e) { setError(e.message); setSaving(false); return }",
"      protocolId = p.id",
"    }",
"    for (let ci = 0; ci < compounds.length; ci++) {",
"      const c = compounds[ci]",
"      const { data: ins } = await supabase.from('compounds').insert({",
"        protocol_id: protocolId,",
"        user_id: user.id,",
"        name: c.name.trim(),",
"        vial_strength: c.vial_strength ? parseFloat(c.vial_strength) : null,",
"        vial_unit: c.vial_unit,",
"        bac_water_ml: c.bac_water_ml ? parseFloat(c.bac_water_ml) : null,",
"        reconstitution_date: c.reconstitution_date,",
"        notes: c.notes.trim(),",
"        vials_in_stock: c.vials_in_stock ? parseInt(c.vials_in_stock) : null,",
"        position: ci",
"      }).select().single()",
"      if (!ins) continue",
"      // Calculate frequency string for backward compat with dashboard",
"      const daysCount = c.days_of_week.length",
"      const freqMap: Record<number,string> = {1:'1x/week',2:'2x/week',3:'3x/week',4:'4x/week',5:'5x/week',6:'6x/week',7:'daily'}",
"      const frequency = freqMap[daysCount] || '1x/week'",
"      await supabase.from('phases').insert({",
"        compound_id: ins.id,",
"        user_id: user.id,",
"        name: 'Phase 1',",
"        dose: parseFloat(c.dose),",
"        dose_unit: c.dose_unit,",
"        start_week: 1,",
"        end_week: parseInt(c.duration_weeks) || 12,",
"        frequency,",
"        day_of_week: c.days_of_week[0] ?? null,",
"        days_of_week: c.days_of_week,",
"        time_of_day: c.time_of_day.toLowerCase(),",
"        duration_weeks: parseInt(c.duration_weeks) || 12,",
"        position: 0",
"      })",
"    }",
"    if (!editingId) {",
"      await supabase.from('protocol_events').insert({ user_id: user.id, protocol_id: protocolId, date: startDate, event_type: 'started', description: 'Started ' + pName })",
"    }",
"    setSaving(false)",
"    setShowForm(false)",
"    setEditingId(null)",
"    load()",
"  }",
"",
"  async function deleteProtocol(id: string) {",
"    if (!confirm('Delete this protocol and all its data?')) return",
"    const supabase = createClient()",
"    await supabase.from('protocols').delete().eq('id', id)",
"    load()",
"  }",
"",
"  const is = { width:'100%', background:inp, border:'1px solid '+bd, borderRadius:'8px', padding:'10px 12px', color:'var(--color-text)', fontSize:'15px', boxSizing:'border-box' as const, colorScheme:'dark' as const }",
"",
"  if (loading) return <main style={{minHeight:'100vh',color:dg,display:'flex',alignItems:'center',justifyContent:'center'}}>Loading...</main>",
"",
"  return (",
"    <main style={{minHeight:'100vh',color:'var(--color-text)',padding:'24px'}}>",
"      <div style={{maxWidth:'540px',margin:'0 auto'}}>",
"        <button onClick={() => router.push('/protocol')} style={{background:'none',border:'none',color:dg,fontSize:'13px',cursor:'pointer',padding:0,marginBottom:'14px'}}>? Dashboard</button>",
"        <div style={{display:'flex',justifyContent:'space-between',alignItems:'center',marginBottom:'24px'}}>",
"          <h1 style={{fontSize:'24px',fontWeight:'bold',color:g}}>My Protocols</h1>",
"          {!showForm && <button onClick={startNew} style={{background:g,color:'var(--color-green-text)',border:'none',borderRadius:'8px',padding:'10px 20px',fontSize:'14px',fontWeight:'700',cursor:'pointer'}}>+ New</button>}",
"        </div>",
"",
"        {showForm && (",
"          <div style={{background:cb,border:'1px solid '+bd,borderRadius:'16px',padding:'20px',marginBottom:'24px'}}>",
"            <h2 style={{fontSize:'18px',fontWeight:'800',marginBottom:'20px',color:g}}>{editingId ? 'Edit Protocol' : 'New Protocol'}</h2>",
"",
"            {compounds.map((c, ci) => (",
"              <div key={ci} style={{marginBottom:'24px'}}>",
"                {compounds.length > 1 && (",
"                  <div style={{display:'flex',justifyContent:'space-between',marginBottom:'12px'}}>",
"                    <span style={{fontSize:'11px',color:mg,fontWeight:'700',letterSpacing:'1px'}}>COMPOUND {ci+1}</span>",
"                    <button onClick={() => setCompounds(compounds.filter((_,i) => i!==ci))} style={{background:'none',border:'none',color:'#ff6b6b',cursor:'pointer',fontSize:'12px'}}>Remove</button>",
"                  </div>",
"                )}",
"",
"                {/* Compound name */}",
"                <div style={{marginBottom:'12px'}}>",
"                  <label style={{display:'block',fontSize:'11px',color:dg,fontWeight:'700',letterSpacing:'1px',marginBottom:'6px'}}>COMPOUND NAME</label>",
"                  <input value={c.name} onChange={e => updateCompound(ci,'name',e.target.value)} placeholder='e.g. Retatrutide' style={is} />",
"                </div>",
"",
"                {/* Vial strength + BAC water */}",
"                <div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:'10px',marginBottom:'12px'}}>",
"                  <div>",
"                    <label style={{display:'block',fontSize:'11px',color:dg,fontWeight:'700',letterSpacing:'1px',marginBottom:'6px'}}>VIAL STRENGTH</label>",
"                    <div style={{display:'flex',gap:'6px'}}>",
"                      <input type='number' value={c.vial_strength} onChange={e => updateCompound(ci,'vial_strength',e.target.value)} placeholder='10' style={{...is,flex:1}} />",
"                      <select value={c.vial_unit} onChange={e => updateCompound(ci,'vial_unit',e.target.value)} style={{...is,width:'65px',flex:'none'}}>",
"                        {UNITS.map(u => <option key={u} value={u}>{u}</option>)}",
"                      </select>",
"                    </div>",
"                  </div>",
"                  <div>",
"                    <label style={{display:'block',fontSize:'11px',color:dg,fontWeight:'700',letterSpacing:'1px',marginBottom:'6px'}}>BAC WATER</label>",
"                    <div style={{display:'flex',gap:'6px',alignItems:'center'}}>",
"                      <input type='number' step='0.5' value={c.bac_water_ml} onChange={e => updateCompound(ci,'bac_water_ml',e.target.value)} placeholder='3' style={{...is,flex:1}} />",
"                      <span style={{fontSize:'13px',color:dg,fontWeight:'600',whiteSpace:'nowrap'}}>mL</span>",
"                    </div>",
"                  </div>",
"                </div>",
"",
"                {/* Reconstitution date */}",
"                <div style={{marginBottom:'12px'}}>",
"                  <label style={{display:'block',fontSize:'11px',color:'#ff6b6b',fontWeight:'700',letterSpacing:'1px',marginBottom:'6px'}}>RECONSTITUTION DATE *</label>",
"                  <input type='date' value={c.reconstitution_date} onChange={e => updateCompound(ci,'reconstitution_date',e.target.value)} style={is} />",
"                </div>",
"",
"                {/* Dose */}",
"                <div style={{marginBottom:'12px'}}>",
"                  <label style={{display:'block',fontSize:'11px',color:dg,fontWeight:'700',letterSpacing:'1px',marginBottom:'6px'}}>DOSE PER INJECTION</label>",
"                  <div style={{display:'flex',gap:'6px'}}>",
"                    <input type='number' step='any' value={c.dose} onChange={e => updateCompound(ci,'dose',e.target.value)} placeholder='e.g. 60' style={{...is,flex:1}} />",
"                    <select value={c.dose_unit} onChange={e => updateCompound(ci,'dose_unit',e.target.value)} style={{...is,width:'75px',flex:'none'}}>",
"                      {UNITS.map(u => <option key={u} value={u}>{u}</option>)}",
"                    </select>",
"                  </div>",
"                </div>",
"",
"                {/* Duration */}",
"                <div style={{marginBottom:'16px'}}>",
"                  <label style={{display:'block',fontSize:'11px',color:dg,fontWeight:'700',letterSpacing:'1px',marginBottom:'6px'}}>PROTOCOL DURATION</label>",
"                  <div style={{display:'flex',gap:'8px',alignItems:'center'}}>",
"                    <input type='number' min='1' max='52' value={c.duration_weeks} onChange={e => updateCompound(ci,'duration_weeks',e.target.value)} style={{...is,width:'80px',flex:'none'}} />",
"                    <span style={{fontSize:'13px',color:dg,fontWeight:'600'}}>weeks</span>",
"                  </div>",
"                </div>",
"",
"                {/* Schedule */}",
"                <div style={{marginBottom:'16px'}}>",
"                  <label style={{display:'block',fontSize:'11px',color:dg,fontWeight:'700',letterSpacing:'1px',marginBottom:'10px'}}>MY SCHEDULE</label>",
"                  <div style={{background:'var(--color-surface)',borderRadius:'10px',padding:'14px'}}>",
"                    <div style={{display:'grid',gridTemplateColumns:'repeat(7,1fr)',gap:'4px',marginBottom:'12px'}}>",
"                      {DAYS.map((day, di) => {",
"                        const dayNum = DAY_NUMS[di]",
"                        const active = c.days_of_week.includes(dayNum)",
"                        return (",
"                          <button key={day} onClick={() => toggleDay(ci, dayNum)} style={{padding:'10px 0',borderRadius:'8px',border:'1px solid '+(active?g:bd),background:active?'var(--color-green-10)':'transparent',color:active?g:dg,fontSize:'11px',fontWeight:'700',cursor:'pointer',display:'flex',flexDirection:'column',alignItems:'center',gap:'4px'}}>",
"                            <span>{day}</span>",
"                            {active && <span style={{width:'5px',height:'5px',borderRadius:'50%',background:g,display:'block'}} />}",
"                          </button>",
"                        )",
"                      })}",
"                    </div>",
"                    {c.days_of_week.length > 0 && (",
"                      <p style={{fontSize:'12px',color:dg,margin:'0 0 10px',textAlign:'center'}}>{c.days_of_week.length}x per week</p>",
"                    )}",
"                    <div style={{display:'grid',gridTemplateColumns:'repeat(4,1fr)',gap:'6px'}}>",
"                      {TIMES.map(t => (",
"                        <button key={t} onClick={() => updateCompound(ci,'time_of_day',t)} style={{padding:'8px 4px',borderRadius:'8px',border:'1px solid '+(c.time_of_day===t?g:bd),background:c.time_of_day===t?'var(--color-green-10)':'transparent',color:c.time_of_day===t?g:dg,fontSize:'11px',fontWeight:'700',cursor:'pointer'}}>",
"                          {t}",
"                        </button>",
"                      ))}",
"                    </div>",
"                  </div>",
"                </div>",
"",
"                {/* Inventory */}",
"                <div style={{marginBottom:'12px'}}>",
"                  <label style={{display:'block',fontSize:'11px',color:dg,fontWeight:'700',letterSpacing:'1px',marginBottom:'6px'}}>VIALS IN STOCK</label>",
"                  <div style={{display:'flex',gap:'8px',alignItems:'center'}}>",
"                    <input type='number' min='0' value={c.vials_in_stock} onChange={e => updateCompound(ci,'vials_in_stock',e.target.value)} placeholder='0' style={{...is,width:'80px',flex:'none'}} />",
"                    <span style={{fontSize:'13px',color:dg,fontWeight:'600'}}>vials</span>",
"                  </div>",
"                </div>",
"",
"                {/* Notes */}",
"                <div style={{marginBottom:'12px'}}>",
"                  <label style={{display:'block',fontSize:'11px',color:dg,fontWeight:'700',letterSpacing:'1px',marginBottom:'6px'}}>NOTES (optional)</label>",
"                  <textarea value={c.notes} onChange={e => updateCompound(ci,'notes',e.target.value)} placeholder='Goals, context, side effects...' rows={2} style={{...is,resize:'none'}} />",
"                </div>",
"",
"                {ci < compounds.length - 1 && <div style={{height:'1px',background:bd,margin:'20px 0'}} />}",
"              </div>",
"            ))}",
"",
"            <button onClick={() => setCompounds([...compounds, newCompound()])} style={{background:'none',border:'1px dashed '+mg,borderRadius:'8px',padding:'10px',width:'100%',color:dg,fontSize:'13px',cursor:'pointer',marginBottom:'16px'}}>+ Add another compound</button>",
"",
"            {/* Start date */}",
"            <div style={{marginBottom:'16px'}}>",
"              <label style={{display:'block',fontSize:'11px',color:dg,fontWeight:'700',letterSpacing:'1px',marginBottom:'6px'}}>PROTOCOL START DATE</label>",
"              <input type='date' value={startDate} onChange={e => setStartDate(e.target.value)} style={is} />",
"            </div>",
"",
"            {error && <div style={{background:'rgba(255,107,107,0.1)',border:'1px solid rgba(255,107,107,0.3)',borderRadius:'8px',padding:'12px',fontSize:'13px',color:'#ff6b6b',marginBottom:'16px'}}>{error}</div>}",
"",
"            <div style={{display:'flex',gap:'8px'}}>",
"              <button onClick={() => {setShowForm(false);setEditingId(null)}} style={{flex:1,background:cb,color:dg,border:'1px solid '+bd,borderRadius:'8px',padding:'12px',fontSize:'14px',cursor:'pointer'}}>Cancel</button>",
"              <button onClick={save} disabled={saving} style={{flex:2,background:saving?'var(--color-green-20)':g,color:saving?mg:'var(--color-green-text)',border:'none',borderRadius:'8px',padding:'12px',fontSize:'14px',fontWeight:'700',cursor:'pointer'}}>{saving?'Saving...':editingId?'Save Changes':'Create Protocol'}</button>",
"            </div>",
"          </div>",
"        )}",
"",
"        {!showForm && protocols.length === 0 && (",
"          <div style={{textAlign:'center',padding:'48px 0'}}>",
"            <p style={{color:dg,marginBottom:'8px'}}>No protocols yet.</p>",
"            <p style={{color:mg,fontSize:'13px'}}>Tap + New to create your first one.</p>",
"          </div>",
"        )}",
"",
"        {!showForm && protocols.map((p: any) => (",
"          <div key={p.id} style={{background:cb,border:'1px solid '+bd,borderRadius:'12px',padding:'16px',marginBottom:'12px'}}>",
"            <div style={{display:'flex',justifyContent:'space-between',alignItems:'flex-start',marginBottom:'10px'}}>",
"              <div>",
"                <h2 style={{fontSize:'17px',fontWeight:'700',color:g,marginBottom:'2px'}}>{p.name}</h2>",
"                <p style={{fontSize:'12px',color:dg}}>Started {new Date(p.start_date+'T12:00:00').toLocaleDateString('en-US',{month:'short',day:'numeric',year:'numeric'})}</p>",
"              </div>",
"              <div style={{display:'flex',gap:'10px'}}>",
"                <button onClick={() => startEdit(p)} style={{background:'none',border:'none',color:dg,cursor:'pointer',fontSize:'13px'}}>Edit</button>",
"                <button onClick={() => deleteProtocol(p.id)} style={{background:'none',border:'none',color:'#ff6b6b',cursor:'pointer',fontSize:'13px'}}>Delete</button>",
"              </div>",
"            </div>",
"            {(p.compounds||[]).map((c: any) => {",
"              const ph = (c.phases||[])[0]",
"              const days = ph?.days_of_week || []",
"              const activeDays = DAYS.filter((_,i) => days.includes(DAY_NUMS[i]))",
"              return (",
"                <div key={c.id} style={{background:'var(--color-surface)',borderRadius:'8px',padding:'10px',marginTop:'6px'}}>",
"                  <div style={{display:'flex',justifyContent:'space-between',marginBottom:'6px'}}>",
"                    <span style={{fontSize:'14px',fontWeight:'700',color:'var(--color-text)'}}>{c.name}</span>",
"                    <span style={{fontSize:'12px',color:dg}}>{ph?.dose}{ph?.dose_unit}</span>",
"                  </div>",
"                  <div style={{display:'flex',gap:'4px',flexWrap:'wrap'}}>",
"                    {activeDays.length > 0 ? activeDays.map(d => (",
"                      <span key={d} style={{fontSize:'10px',fontWeight:'700',color:g,background:'var(--color-green-10)',padding:'2px 6px',borderRadius:'4px'}}>{d}</span>",
"                    )) : <span style={{fontSize:'11px',color:mg}}>No schedule set</span>}",
"                    {ph?.time_of_day && <span style={{fontSize:'10px',color:dg,marginLeft:'4px'}}>\u00b7 {ph.time_of_day}</span>}",
"                  </div>",
"                  {ph?.duration_weeks && <p style={{fontSize:'11px',color:mg,marginTop:'4px',marginBottom:0}}>{ph.duration_weeks} week protocol</p>}",
"                </div>",
"              )",
"            })}",
"          </div>",
"        ))}",
"      </div>",
"    </main>",
"  )",
"}",
];

fs.writeFileSync('app/protocol/manage/page.tsx', lines.join('\n'), 'utf8');
console.log('Done! Size:', fs.statSync('app/protocol/manage/page.tsx').size);
