const fs = require('fs');

const lines = [
"'use client'",
"",
"type LogEntry = { compound_id: string; taken: boolean; discomfort: number }",
"",
"type Props = {",
"  activeProtocols: any[]",
"  activeCompoundTab: string | null",
"  logs: Record<string, LogEntry>",
"  allLogs: { compound_id: string; taken: boolean; date: string }[]",
"  totalLost: string | null",
"}",
"",
"const COMPOUND_COLORS: Record<string, string> = {",
"  retatrutide: '#39ff14', semaglutide: '#39ff14', tirzepatide: '#39ff14', liraglutide: '#39ff14',",
"  bpc: '#06b6d4', tb: '#06b6d4', cjc: '#8b5cf6', ipamorelin: '#8b5cf6',",
"  ghk: '#f59e0b', hcg: '#f97316', mots: '#f43f5e', kpv: '#a3e635',",
"}",
"",
"function getCompoundColor(name: string): string {",
"  const lower = name.toLowerCase()",
"  for (const [key, color] of Object.entries(COMPOUND_COLORS)) {",
"    if (lower.includes(key)) return color",
"  }",
"  return '#6c63ff'",
"}",
"",
"function DynamicVial({ name, color, fillPct }: { name: string; color: string; fillPct: number }) {",
"  const short = name.split('/')[0].split(' ')[0].slice(0, 8)",
"  const bodyTop = 18",
"  const bodyH = 62",
"  const fill = Math.max(0, Math.min(1, fillPct))",
"  const fillH = bodyH * fill",
"  const fillY = bodyTop + bodyH - fillH",
"  return (",
"    <svg width='72' height='110' viewBox='0 0 64 110' fill='none' xmlns='http://www.w3.org/2000/svg'>",
"      <rect x='20' y='0' width='24' height='14' rx='4' fill={color} opacity='0.9'/>",
"      <rect x='24' y='12' width='16' height='6' rx='2' fill={color} opacity='0.7'/>",
"      <rect x='12' y={bodyTop} width='40' height={bodyH} rx='8' fill='#1a1a2e' stroke={color} strokeWidth='1.5'/>",
"      {fillH > 0 && (",
"        <rect x='13.5' y={fillY} width='37' height={fillH} rx={fillH >= bodyH ? '6' : '0 0 6 6'} fill={color} opacity='0.35'/>",
"      )}",
"      <rect x='13.5' y={fillY} width='37' height='3' fill={color} opacity={fill > 0.05 ? 0.6 : 0}/>",
"      <rect x='16' y={bodyTop + 2} width='6' height='28' rx='3' fill='white' opacity='0.12'/>",
"      <text x='32' y='54' textAnchor='middle' fontSize='7' fontWeight='800' fill={color} fontFamily='Inter,sans-serif'>{short}</text>",
"      <rect x='12' y={bodyTop + bodyH - 4} width='40' height='4' rx='2' fill={color} opacity='0.2'/>",
"      {[0.25, 0.5, 0.75].map((tick) => (",
"        <line key={tick} x1='44' y1={bodyTop + bodyH * (1 - tick)} x2='50' y2={bodyTop + bodyH * (1 - tick)} stroke={color} strokeWidth='0.8' opacity='0.3'/>",
"      ))}",
"    </svg>",
"  )",
"}",
"",
"export default function HeroProtocolCard({ activeProtocols, activeCompoundTab, logs, allLogs, totalLost }: Props) {",
"  if (!activeProtocols || activeProtocols.length === 0) return null",
"",
"  // Find the active compound across all protocols",
"  let activeCompound: any = null",
"  let activeProtocol: any = null",
"  for (const p of activeProtocols) {",
"    for (const c of (p.compounds || [])) {",
"      if (c.id === activeCompoundTab) { activeCompound = c; activeProtocol = p; break }",
"    }",
"    if (activeCompound) break",
"  }",
"  // Fallback to first compound",
"  if (!activeCompound) {",
"    activeProtocol = activeProtocols[0]",
"    activeCompound = activeProtocol?.compounds?.[0]",
"  }",
"  if (!activeCompound || !activeProtocol) return null",
"",
"  const color = getCompoundColor(activeCompound.name)",
"",
"  // Correct week for this specific compound's protocol",
"  const daysIn = Math.max(0, Math.floor((Date.now() - new Date(activeProtocol.start_date + 'T00:00:00').getTime()) / 86400000))",
"  const compoundWeek = Math.max(1, Math.floor(daysIn / 7) + 1)",
"",
"  // Protocol progress",
"  const phases = (activeCompound.phases || []).sort((a: any, b: any) => b.end_week - a.end_week)",
"  const lastPhase = phases[0]",
"  const totalDays = lastPhase ? lastPhase.end_week * 7 : 84",
"  const progress = Math.min(100, Math.round((daysIn / totalDays) * 100))",
"",
"  // Current phase",
"  const currentPhase = (activeCompound.phases || []).find((ph: any) => compoundWeek >= ph.start_week && compoundWeek <= ph.end_week) || activeCompound.phases?.[0]",
"",
"  // Vial status",
"  const reconDate = activeCompound.reconstitution_date",
"  const bacWater = activeCompound.bac_water_ml || 0",
"  const vialStrength = activeCompound.vial_strength || 0",
"  let vialDaysLeft: number | null = null",
"  let mlRemaining: number | null = null",
"  let fillPct = 1",
"",
"  if (reconDate && bacWater > 0 && currentPhase) {",
"    const daysSinceRecon = Math.floor((Date.now() - new Date(reconDate + 'T00:00:00').getTime()) / 86400000)",
"    vialDaysLeft = 28 - daysSinceRecon",
"",
"    // Calculate mL used from injection logs",
"    const concentration = vialStrength > 0 ? (vialStrength * 1000) / bacWater : 0",
"    const mlPerDose = concentration > 0 ? (currentPhase.dose * 1000) / concentration : 0",
"    const takenCount = allLogs.filter((l: any) => l.compound_id === activeCompound.id && l.taken).length",
"    const mlUsed = takenCount * mlPerDose",
"    mlRemaining = Math.max(0, bacWater - mlUsed)",
"    fillPct = bacWater > 0 ? mlRemaining / bacWater : 1",
"  }",
"",
"  return (",
"    <div style={{background:'linear-gradient(135deg, #111111 0%, #1a1a2e 100%)',borderRadius:'16px',padding:'20px',marginBottom:'16px',overflow:'hidden',position:'relative',border:'1px solid rgba(255,255,255,0.08)',transition:'all 0.3s ease'}}>",
"      <div style={{position:'absolute',top:'-20px',right:'-20px',width:'140px',height:'140px',borderRadius:'50%',background:color.replace('#','rgba(') + ',0.06)',filter:'blur(40px)',pointerEvents:'none'}} />",
"",
"      <div style={{display:'flex',justifyContent:'space-between',alignItems:'flex-start'}}>",
"        <div style={{flex:1,minWidth:0}}>",
"          <div style={{fontSize:'10px',fontWeight:'700',color:'rgba(255,255,255,0.4)',letterSpacing:'2px',marginBottom:'6px'}}>ACTIVE COMPOUND</div>",
"          <h2 style={{fontSize:'22px',fontWeight:'900',color:'white',marginBottom:'8px',lineHeight:'1.2'}}>{activeCompound.name}</h2>",
"",
"          <div style={{display:'flex',alignItems:'center',gap:'6px',marginBottom:'14px',flexWrap:'wrap'}}>",
"            <span style={{fontSize:'12px',fontWeight:'700',color:color,background:color+'18',padding:'3px 8px',borderRadius:'20px'}}>Week {compoundWeek}</span>",
"            {currentPhase && <span style={{fontSize:'12px',color:'rgba(255,255,255,0.5)'}}>{currentPhase.dose}{currentPhase.dose_unit} \u00b7 {currentPhase.frequency}</span>}",
"            {totalLost && parseFloat(totalLost) > 0 && (",
"              <span style={{fontSize:'12px',fontWeight:'700',color:'#f59e0b',background:'rgba(245,158,11,0.1)',padding:'3px 8px',borderRadius:'20px'}}>-{totalLost} lbs</span>",
"            )}",
"          </div>",
"",
"          {vialDaysLeft !== null && mlRemaining !== null && (",
"            <div style={{marginBottom:'12px',display:'flex',gap:'12px'}}>",
"              <div>",
"                <div style={{fontSize:'9px',color:'rgba(255,255,255,0.3)',fontWeight:'600',letterSpacing:'1px',marginBottom:'2px'}}>VIAL EXPIRES</div>",
"                <div style={{fontSize:'13px',fontWeight:'700',color:vialDaysLeft<=5?'#ff6b6b':vialDaysLeft<=10?'#f59e0b':'rgba(255,255,255,0.8)'}}>{vialDaysLeft}d left</div>",
"              </div>",
"              <div>",
"                <div style={{fontSize:'9px',color:'rgba(255,255,255,0.3)',fontWeight:'600',letterSpacing:'1px',marginBottom:'2px'}}>EST. REMAINING</div>",
"                <div style={{fontSize:'13px',fontWeight:'700',color:'rgba(255,255,255,0.8)'}}>{mlRemaining.toFixed(2)} mL</div>",
"              </div>",
"            </div>",
"          )}",
"",
"          <div>",
"            <div style={{display:'flex',justifyContent:'space-between',marginBottom:'4px'}}>",
"              <span style={{fontSize:'9px',color:'rgba(255,255,255,0.3)',fontWeight:'600',letterSpacing:'1px'}}>PROTOCOL PROGRESS</span>",
"              <span style={{fontSize:'9px',color:'rgba(255,255,255,0.5)',fontWeight:'700'}}>{progress}%</span>",
"            </div>",
"            <div style={{height:'4px',background:'rgba(255,255,255,0.08)',borderRadius:'2px',overflow:'hidden'}}>",
"              <div style={{height:'100%',width:progress+'%',background:'linear-gradient(90deg,'+color+','+color+'99)',borderRadius:'2px',transition:'width 0.5s ease'}} />",
"            </div>",
"          </div>",
"        </div>",
"",
"        <div style={{marginLeft:'16px',flexShrink:0,filter:'drop-shadow(0 4px 12px rgba(0,0,0,0.5))'}}>",
"          <DynamicVial name={activeCompound.name} color={color} fillPct={fillPct} />",
"        </div>",
"      </div>",
"    </div>",
"  )",
"}",
];

fs.writeFileSync('components/dashboard/HeroProtocolCard.tsx', lines.join('\n'), 'utf8');
console.log('Done! Size:', fs.statSync('components/dashboard/HeroProtocolCard.tsx').size, 'bytes');
