const fs = require('fs');
const content = [
"'use client'",
"",
"import { useState } from 'react'",
"import { createClient } from '../../../lib/supabase'",
"import { useRouter } from 'next/navigation'",
"",
"export default function LoginPage() {",
"  const [email, setEmail] = useState('')",
"  const [code, setCode] = useState('')",
"  const [step, setStep] = useState<'email'|'code'>('email')",
"  const [loading, setLoading] = useState(false)",
"  const [error, setError] = useState('')",
"  const router = useRouter()",
"",
"  async function sendCode() {",
"    setError('')",
"    if (!email || !email.includes('@')) {",
"      setError('Please enter a valid email address.')",
"      return",
"    }",
"    setLoading(true)",
"    const supabase = createClient()",
"    const { error } = await supabase.auth.signInWithOtp({",
"      email,",
"      options: { shouldCreateUser: true }",
"    })",
"    if (error) { setError(error.message); setLoading(false); return }",
"    setStep('code')",
"    setLoading(false)",
"  }",
"",
"  async function verifyCode() {",
"    setError('')",
"    if (!code || code.length < 6) {",
"      setError('Please enter the 6-digit code from your email.')",
"      return",
"    }",
"    setLoading(true)",
"    const supabase = createClient()",
"    const { error } = await supabase.auth.verifyOtp({",
"      email,",
"      token: code,",
"      type: 'email'",
"    })",
"    if (error) { setError('Invalid or expired code. Try again.'); setLoading(false); return }",
"    router.push('/protocol')",
"  }",
"",
"  if (step === 'code') {",
"    return (",
"      <main style={{minHeight:'100vh',background:'#030712',color:'white',display:'flex',flexDirection:'column',alignItems:'center',justifyContent:'center',padding:'24px'}}>",
"        <div style={{maxWidth:'400px',width:'100%'}}>",
"          <h1 style={{fontSize:'28px',fontWeight:'bold',marginBottom:'8px'}}>Check your email</h1>",
"          <p style={{color:'#6b7280',marginBottom:'32px'}}>",
"            We sent a 6-digit code to <strong style={{color:'white'}}>{email}</strong>. Enter it below.",
"          </p>",
"          <div style={{marginBottom:'16px'}}>",
"            <label style={{display:'block',fontSize:'14px',fontWeight:'500',marginBottom:'6px'}}>6-digit code</label>",
"            <input",
"              type='number'",
"              value={code}",
"              onChange={e => setCode(e.target.value)}",
"              onKeyDown={e => e.key === 'Enter' && verifyCode()}",
"              placeholder='123456'",
"              maxLength={6}",
"              style={{width:'100%',background:'#1f2937',border:'1px solid #374151',borderRadius:'6px',padding:'12px',color:'white',fontSize:'24px',letterSpacing:'8px',textAlign:'center',boxSizing:'border-box',outline:'none'}}",
"            />",
"          </div>",
"          {error && (",
"            <div style={{background:'#450a0a',border:'1px solid #991b1b',borderRadius:'6px',padding:'10px',fontSize:'14px',color:'#fca5a5',marginBottom:'16px'}}>{error}</div>",
"          )}",
"          <button onClick={verifyCode} disabled={loading} style={{width:'100%',background:loading?'#1d4ed8':'#2563eb',color:'white',fontWeight:'600',padding:'12px',borderRadius:'6px',border:'none',fontSize:'16px',cursor:loading?'not-allowed':'pointer',marginBottom:'12px'}}>",
"            {loading ? 'Verifying...' : 'Sign in'}",
"          </button>",
"          <button onClick={() => { setStep('email'); setCode(''); setError('') }} style={{width:'100%',background:'none',border:'none',color:'#6b7280',fontSize:'14px',cursor:'pointer'}}>",
"            Use a different email",
"          </button>",
"          <p style={{color:'#4b5563',fontSize:'12px',marginTop:'16px',textAlign:'center'}}>No email? Check your spam folder. Code expires in 10 minutes.</p>",
"        </div>",
"      </main>",
"    )",
"  }",
"",
"  return (",
"    <main style={{minHeight:'100vh',background:'#030712',color:'white',display:'flex',flexDirection:'column',alignItems:'center',justifyContent:'center',padding:'24px'}}>",
"      <div style={{maxWidth:'400px',width:'100%'}}>",
"        <h1 style={{fontSize:'28px',fontWeight:'bold',marginBottom:'8px'}}>Protocol</h1>",
"        <p style={{color:'#6b7280',marginBottom:'32px'}}>Enter your email to sign in or create an account.</p>",
"        <div style={{marginBottom:'16px'}}>",
"          <label style={{display:'block',fontSize:'14px',fontWeight:'500',marginBottom:'6px'}}>Email address</label>",
"          <input",
"            type='email'",
"            value={email}",
"            onChange={e => setEmail(e.target.value)}",
"            onKeyDown={e => e.key === 'Enter' && sendCode()}",
"            placeholder='you@example.com'",
"            style={{width:'100%',background:'#1f2937',border:'1px solid #374151',borderRadius:'6px',padding:'10px 12px',color:'white',fontSize:'16px',outline:'none',boxSizing:'border-box'}}",
"          />",
"        </div>",
"        {error && (",
"          <div style={{background:'#450a0a',border:'1px solid #991b1b',borderRadius:'6px',padding:'10px',fontSize:'14px',color:'#fca5a5',marginBottom:'16px'}}>{error}</div>",
"        )}",
"        <button onClick={sendCode} disabled={loading} style={{width:'100%',background:loading?'#1d4ed8':'#2563eb',color:'white',fontWeight:'600',padding:'12px',borderRadius:'6px',border:'none',fontSize:'16px',cursor:loading?'not-allowed':'pointer'}}>",
"          {loading ? 'Sending...' : 'Send code'}",
"        </button>",
"        <p style={{color:'#4b5563',fontSize:'12px',marginTop:'24px',lineHeight:'1.6',textAlign:'center'}}>",
"          By signing in you agree to use this tool for personal harm reduction tracking only. Not medical advice.",
"        </p>",
"      </div>",
"    </main>",
"  )",
"}",
].join('\n');
fs.writeFileSync('app/auth/login/page.tsx', content, 'utf8');
console.log('Done');
