const fs = require('fs');
const content = [
"'use client'",
"",
"import { usePathname, useRouter } from 'next/navigation'",
"import { createClient } from '../lib/supabase'",
"",
"export default function BottomNav() {",
"  const pathname = usePathname()",
"  const router = useRouter()",
"  const links = [",
"    { href: '/calculator', label: 'Pep Calc' },",
"    { href: '/protocol', label: 'Protocol' },",
"    { href: '/journal', label: 'Journal' },",
"    { href: '/learn', label: 'Learn' },",
"  ]",
"",
"  async function handleSignOut() {",
"    const supabase = createClient()",
"    await supabase.auth.signOut()",
"    router.push('/auth/login')",
"  }",
"",
"  return (",
"    <nav style={{",
"      position:'fixed',",
"      bottom:0,",
"      left:0,",
"      right:0,",
"      background:'#000000',",
"      borderTop:'1px solid #1a1a1a',",
"      display:'flex',",
"      justifyContent:'space-around',",
"      alignItems:'center',",
"      padding:'14px 16px 28px 16px',",
"      zIndex:50",
"    }}>",
"      {links.map((link) => {",
"        const isActive = pathname === link.href",
"        return (",
"          <a",
"            key={link.href}",
"            href={link.href}",
"            style={{",
"              display:'flex',",
"              flexDirection:'column',",
"              alignItems:'center',",
"              gap:'4px',",
"              textDecoration:'none',",
"              minWidth:'52px',",
"              flex:1",
"            }}",
"          >",
"            <span style={{",
"              width:'5px',",
"              height:'5px',",
"              borderRadius:'50%',",
"              background:isActive?'#39ff14':'transparent',",
"              display:'block'",
"            }} />",
"            <span style={{",
"              color:isActive?'#39ff14':'#4a7a4a',",
"              fontSize:'13px',",
"              fontWeight:isActive?'600':'400',",
"              textAlign:'center'",
"            }}>",
"              {link.label}",
"            </span>",
"          </a>",
"        )",
"      })}",
"      <button",
"        onClick={handleSignOut}",
"        style={{",
"          display:'flex',",
"          flexDirection:'column',",
"          alignItems:'center',",
"          gap:'4px',",
"          background:'none',",
"          border:'none',",
"          minWidth:'52px',",
"          flex:1,",
"          cursor:'pointer',",
"          padding:0",
"        }}",
"      >",
"        <span style={{width:'5px',height:'5px',borderRadius:'50%',background:'transparent',display:'block'}} />",
"        <span style={{color:'#4a7a4a',fontSize:'13px'}}>Sign out</span>",
"      </button>",
"    </nav>",
"  )",
"}",
].join('\n');
fs.writeFileSync('components/BottomNav.tsx', content, 'utf8');
console.log('Done');
