const fs = require('fs');
const lines = [];
lines.push("'use client'");
lines.push("");
lines.push("import { usePathname } from 'next/navigation'");
lines.push("");
lines.push("export default function BottomNav() {");
lines.push("  const pathname = usePathname()");
lines.push("  const links = [");
lines.push("    { href: '/calculator', label: 'Calc' },");
lines.push("    { href: '/protocol', label: 'Protocol' },");
lines.push("    { href: '/journal', label: 'Journal' },");
lines.push("    { href: '/community', label: 'Community' },");
lines.push("    { href: '/profile', label: 'Profile' },");
lines.push("  ]");
lines.push("  return (");
lines.push("    <nav style={{position:'fixed',bottom:0,left:0,right:0,background:'#000000',borderTop:'1px solid #1a1a1a',display:'flex',justifyContent:'space-around',alignItems:'center',padding:'14px 8px 28px 8px',zIndex:50}}>"); 
lines.push("      {links.map((link) => {"); 
lines.push("        const isActive = pathname === link.href || pathname.startsWith(link.href+'/') && link.href !== '/'"); 
lines.push("        return ("); 
lines.push("          <a key={link.href} href={link.href} style={{display:'flex',flexDirection:'column',alignItems:'center',gap:'4px',textDecoration:'none',flex:1}}>"); 
lines.push("            <span style={{width:'5px',height:'5px',borderRadius:'50%',background:isActive?'#39ff14':'transparent',display:'block'}} />"); 
lines.push("            <span style={{color:isActive?'#39ff14':'#4dbd4d',fontSize:'11px',fontWeight:'700',textAlign:'center'}}>"); 
lines.push("              {link.label}"); 
lines.push("            </span>"); 
lines.push("          </a>"); 
lines.push("        )"); 
lines.push("      })}"); 
lines.push("    </nav>"); 
lines.push("  )"); 
lines.push("}");
fs.writeFileSync('components/BottomNav.tsx', lines.join('\n'), 'utf8');
console.log('Done');
