const fs = require('fs');
const lines = [];
lines.push("const CACHE_NAME = 'protocol-v2'");
lines.push("");
lines.push("const STATIC_ASSETS = [");
lines.push("  '/',");
lines.push("  '/calculator',");
lines.push("  '/protocol',");
lines.push("  '/journal',");
lines.push("  '/learn',");
lines.push("  '/manifest.json',");
lines.push("]");
lines.push("");
lines.push("self.addEventListener('install', (event) => {");
lines.push("  event.waitUntil(");
lines.push("    caches.open(CACHE_NAME).then((cache) => cache.addAll(STATIC_ASSETS))");
lines.push("  )");
lines.push("  self.skipWaiting()");
lines.push("})");
lines.push("");
lines.push("self.addEventListener('activate', (event) => {");
lines.push("  event.waitUntil(");
lines.push("    caches.keys().then((names) =>");
lines.push("      Promise.all(names.filter(n => n !== CACHE_NAME).map(n => caches.delete(n)))");
lines.push("    )");
lines.push("  )");
lines.push("  self.clients.claim()");
lines.push("})");
lines.push("");
lines.push("self.addEventListener('fetch', (event) => {");
lines.push("  const { request } = event");
lines.push("  const url = new URL(request.url)");
lines.push("  if (request.method !== 'GET') return");
lines.push("  if (url.hostname.includes('supabase.co')) return");
lines.push("  event.respondWith(");
lines.push("    caches.match(request).then((cached) => {");
lines.push("      if (cached) return cached");
lines.push("      return fetch(request).then((response) => {");
lines.push("        if (!response || response.status !== 200) return response");
lines.push("        const copy = response.clone()");
lines.push("        caches.open(CACHE_NAME).then((cache) => cache.put(request, copy))");
lines.push("        return response");
lines.push("      }).catch(() => caches.match('/'))");
lines.push("    })");
lines.push("  )");
lines.push("})");
lines.push("");
lines.push("self.addEventListener('push', (event) => {");
lines.push("  const data = event.data ? event.data.json() : {}");
lines.push("  const title = data.title || 'Protocol'");
lines.push("  const options = {");
lines.push("    body: data.body || 'You have a new notification.',");
lines.push("    icon: '/icon-192.png',");
lines.push("    badge: '/icon-192.png',");
lines.push("    data: { url: data.url || '/' },");
lines.push("  }");
lines.push("  event.waitUntil(self.registration.showNotification(title, options))");
lines.push("})");
lines.push("");
lines.push("self.addEventListener('notificationclick', (event) => {");
lines.push("  event.notification.close()");
lines.push("  const url = event.notification.data?.url || '/'");
lines.push("  event.waitUntil(");
lines.push("    clients.matchAll({ type: 'window' }).then((windowClients) => {");
lines.push("      for (const client of windowClients) {");
lines.push("        if (client.url.includes(self.location.origin) && 'focus' in client) {");
lines.push("          client.navigate(url)");
lines.push("          return client.focus()");
lines.push("        }");
lines.push("      }");
lines.push("      if (clients.openWindow) return clients.openWindow(url)");
lines.push("    })");
lines.push("  )");
lines.push("})");
fs.writeFileSync('public/sw.js', lines.join('\n'), 'utf8');
console.log('Done');
