const fs = require('fs');
const content = [
"'use client'",
"",
"import { usePathname, useRouter } from 'next/navigation'",
"import { createClient } from '../lib/supabase'",
"",
"export default function BottomNav() {",
"  const pathname = usePathname()",
"  const router = useRouter()",
"  const links = [",
"    { href: '/calculator', label: 'Calc' },",
"    { href: '/protocol', label: 'Protocol' },",
"    { href: '/journal', label: 'Journal' },",
"    { href: '/learn', label: 'Learn' },",
"  ]",
"",
"  async function handleSignOut() {",
"    const supabase = createClient()",
"    await supabase.auth.signOut()",
"    router.push('/auth/login')",
"  }",
"",
"  return (",
"    <nav style={{position:'fixed',bottom:0,left:0,right:0,background:'#111827',borderTop:'1px solid #1f2937',display:'flex',justifyContent:'space-around',alignItems:'center',padding:'8px 0 20px 0',zIndex:50}}>",
"      {links.map((link) => {",
"        const isActive = pathname === link.href",
"        return (",
"          <a",
"            key={link.href}",
"            href={link.href}",
"            style={{display:'flex',flexDirection:'column',alignItems:'center',gap:'3px',textDecoration:'none',minWidth:'56px'}}",
"          >",
"            <span style={{width:'4px',height:'4px',borderRadius:'50%',background:isActive?'#3b82f6':'transparent',display:'block'}} />",
"            <span style={{color:isActive?'#ffffff':'#6b7280',fontSize:'12px',fontWeight:isActive?'600':'400'}}>",
"              {link.label}",
"            </span>",
"          </a>",
"        )",
"      })}",
"      <button",
"        onClick={handleSignOut}",
"        style={{display:'flex',flexDirection:'column',alignItems:'center',gap:'3px',background:'none',border:'none',minWidth:'56px',cursor:'pointer'}}",
"      >",
"        <span style={{width:'4px',height:'4px',borderRadius:'50%',background:'transparent',display:'block'}} />",
"        <span style={{color:'#6b7280',fontSize:'12px'}}>Sign out</span>",
"      </button>",
"    </nav>",
"  )",
"}",
].join('\n');
fs.writeFileSync('components/BottomNav.tsx', content, 'utf8');
console.log('Done');
