const fs = require('fs');
const lines = [];
lines.push("'use client'");
lines.push("");
lines.push("import { useState, useEffect } from 'react'");
lines.push("import { createClient } from '../../lib/supabase'");
lines.push("import { useRouter } from 'next/navigation'");
lines.push("");
lines.push("const ADMIN_ID = '41266062-c8a7-4a52-aa9b-c1fb96d1c483'");
lines.push("");
lines.push("type Post = {");
lines.push("  id: string");
lines.push("  username: string");
lines.push("  content: string");
lines.push("  tag: string | null");
lines.push("  flagged: boolean");
lines.push("  created_at: string");
lines.push("  cohort_id: string");
lines.push("  cohorts: { name: string }");
lines.push("}");
lines.push("");
lines.push("export default function AdminPage() {");
lines.push("  const [posts, setPosts] = useState<Post[]>([])");
lines.push("  const [loading, setLoading] = useState(true)");
lines.push("  const [authorized, setAuthorized] = useState(false)");
lines.push("  const [filter, setFilter] = useState<'all'|'flagged'>('all')");
lines.push("  const router = useRouter()");
lines.push("  const g = '#39ff14'");
lines.push("  const dg = '#4dbd4d'");
lines.push("  const mg = '#2d5a2d'");
lines.push("  const cb = '#0d0d0d'");
lines.push("  const bd = '#1a1a1a'");
lines.push("");
lines.push("  useEffect(() => { checkAuth() }, [])");
lines.push("");
lines.push("  async function checkAuth() {");
lines.push("    const supabase = createClient()");
lines.push("    const { data: { user } } = await supabase.auth.getUser()");
lines.push("    if (!user || user.id !== ADMIN_ID) { router.push('/'); return }");
lines.push("    setAuthorized(true)");
lines.push("    loadPosts()");
lines.push("  }");
lines.push("");
lines.push("  async function loadPosts() {");
lines.push("    setLoading(true)");
lines.push("    const supabase = createClient()");
lines.push("    const { data } = await supabase");
lines.push("      .from('cohort_posts')");
lines.push("      .select('*, cohorts(name)')");
lines.push("      .order('created_at', { ascending: false })");
lines.push("    setPosts(data || [])");
lines.push("    setLoading(false)");
lines.push("  }");
lines.push("");
lines.push("  async function deletePost(id: string) {");
lines.push("    const supabase = createClient()");
lines.push("    await supabase.from('cohort_posts').delete().eq('id', id)");
lines.push("    loadPosts()");
lines.push("  }");
lines.push("");
lines.push("  async function toggleFlag(id: string, current: boolean) {");
lines.push("    const supabase = createClient()");
lines.push("    await supabase.from('cohort_posts').update({ flagged: !current }).eq('id', id)");
lines.push("    loadPosts()");
lines.push("  }");
lines.push("");
lines.push("  function timeAgo(dateStr: string) {");
lines.push("    const diff = Date.now() - new Date(dateStr).getTime()");
lines.push("    const mins = Math.floor(diff / 60000)");
lines.push("    if (mins < 60) return mins + 'm ago'");
lines.push("    const hrs = Math.floor(mins / 60)");
lines.push("    if (hrs < 24) return hrs + 'h ago'");
lines.push("    return Math.floor(hrs / 24) + 'd ago'");
lines.push("  }");
lines.push("");
lines.push("  if (!authorized) return null");
lines.push("");
lines.push("  const filteredPosts = filter === 'flagged' ? posts.filter(p => p.flagged) : posts");
lines.push("");
lines.push("  return (");
lines.push("    <main style={{minHeight:'100vh',background:'#000000',color:'white',padding:'24px'}}>"); 
lines.push("      <div style={{maxWidth:'600px',margin:'0 auto'}}>"); 
lines.push("        <div style={{display:'flex',justifyContent:'space-between',alignItems:'center',marginBottom:'8px'}}>"); 
lines.push("          <h1 style={{fontSize:'24px',fontWeight:'bold',color:g}}>Admin</h1>"); 
lines.push("          <span style={{fontSize:'12px',color:mg}}>{posts.length} total posts</span>"); 
lines.push("        </div>"); 
lines.push("        <p style={{color:mg,fontSize:'13px',marginBottom:'24px'}}>Moderator view — all cohort posts.</p>"); 
lines.push("        <div style={{display:'flex',gap:'8px',marginBottom:'24px'}}>"); 
lines.push("          <button onClick={() => setFilter('all')} style={{background:filter==='all'?'#0a1a0a':'none',border:'1px solid '+(filter==='all'?mg:bd),color:filter==='all'?dg:mg,fontSize:'13px',padding:'6px 14px',borderRadius:'6px',cursor:'pointer'}}>All posts</button>"); 
lines.push("          <button onClick={() => setFilter('flagged')} style={{background:filter==='flagged'?'#1a0000':'none',border:'1px solid '+(filter==='flagged'?'#4a0000':bd),color:filter==='flagged'?'#ff6b6b':mg,fontSize:'13px',padding:'6px 14px',borderRadius:'6px',cursor:'pointer'}}>Flagged {posts.filter(p=>p.flagged).length > 0 && '('+posts.filter(p=>p.flagged).length+')'}</button>"); 
lines.push("        </div>"); 
lines.push("        {loading && <p style={{color:mg}}>Loading...</p>}"); 
lines.push("        {!loading && filteredPosts.length === 0 && <p style={{color:mg,textAlign:'center',padding:'48px 0'}}>No posts.</p>}"); 
lines.push("        {filteredPosts.map(post => ("); 
lines.push("          <div key={post.id} style={{background:post.flagged?'#1a0000':cb,border:'1px solid '+(post.flagged?'#4a0000':bd),borderRadius:'8px',padding:'16px',marginBottom:'12px'}}>"); 
lines.push("            <div style={{display:'flex',justifyContent:'space-between',alignItems:'flex-start',marginBottom:'8px'}}>"); 
lines.push("              <div>"); 
lines.push("                <span style={{fontSize:'13px',fontWeight:'700',color:dg}}>@{post.username}</span>"); 
lines.push("                <span style={{fontSize:'11px',color:mg,marginLeft:'8px'}}>{post.cohorts?.name}</span>"); 
lines.push("                {post.tag && <span style={{fontSize:'10px',color:mg,background:'#0a1a0a',padding:'2px 6px',borderRadius:'4px',marginLeft:'8px'}}>{post.tag}</span>}"); 
lines.push("              </div>"); 
lines.push("              <span style={{fontSize:'11px',color:mg}}>{timeAgo(post.created_at)}</span>"); 
lines.push("            </div>"); 
lines.push("            <p style={{fontSize:'14px',lineHeight:'1.6',margin:'0 0 12px 0',color:'#e5e5e5'}}>{post.content}</p>"); 
lines.push("            <div style={{display:'flex',gap:'8px'}}>"); 
lines.push("              <button onClick={() => toggleFlag(post.id, post.flagged)} style={{background:'none',border:'1px solid '+(post.flagged?'#4a0000':bd),color:post.flagged?'#ff6b6b':mg,fontSize:'12px',padding:'4px 10px',borderRadius:'4px',cursor:'pointer'}}>{post.flagged?'Unflag':'Flag'}</button>"); 
lines.push("              <button onClick={() => deletePost(post.id)} style={{background:'#1a0000',border:'1px solid #4a0000',color:'#ff6b6b',fontSize:'12px',padding:'4px 10px',borderRadius:'4px',cursor:'pointer'}}>Delete</button>"); 
lines.push("            </div>"); 
lines.push("          </div>"); 
lines.push("        ))}"); 
lines.push("      </div>"); 
lines.push("    </main>"); 
lines.push("  )"); 
lines.push("}");
fs.writeFileSync('app/admin/page.tsx', lines.join('\n'), 'utf8');
console.log('Done');
