const fs = require('fs');
const content = [
"'use client'",
"",
"import { useEffect } from 'react'",
"import { useRouter } from 'next/navigation'",
"import { createClient } from '../lib/supabase'",
"",
"export default function Home() {",
"  const router = useRouter()",
"",
"  useEffect(() => {",
"    async function checkUser() {",
"      const supabase = createClient()",
"      const { data: { user } } = await supabase.auth.getUser()",
"      if (user) {",
"        router.push('/protocol')",
"      }",
"    }",
"    checkUser()",
"  }, [])",
"",
"  return (",
"    <main style={{minHeight:'100vh',background:'#030712',color:'white',display:'flex',flexDirection:'column',alignItems:'center',justifyContent:'center',padding:'24px'}}>",
"      <h1 style={{fontSize:'32px',fontWeight:'bold',marginBottom:'8px'}}>Protocol</h1>",
"      <p style={{color:'#6b7280',marginBottom:'32px',textAlign:'center'}}>Your personal wellness protocol tracker.</p>",
"      <a href='/auth/login' style={{background:'#2563eb',color:'white',textDecoration:'none',fontWeight:'600',padding:'12px 32px',borderRadius:'8px',fontSize:'16px'}}>",
"        Get started",
"      </a>",
"      <a href='/calculator' style={{marginTop:'16px',color:'#6b7280',fontSize:'13px',textDecoration:'none'}}>",
"        Use reconstitution calculator without signing in",
"      </a>",
"    </main>",
"  )",
"}",
].join('\n');
fs.writeFileSync('app/page.tsx', content, 'utf8');
console.log('Done');
