const fs = require('fs');
const lines = [];
lines.push("'use client'");
lines.push("");
lines.push("import { useState, useEffect } from 'react'");
lines.push("import { createClient } from '../../lib/supabase'");
lines.push("import { useRouter } from 'next/navigation'");
lines.push("");
lines.push("export default function ProfilePage() {");
lines.push("  const [email, setEmail] = useState('')");
lines.push("  const [createdAt, setCreatedAt] = useState('')");
lines.push("  const [loading, setLoading] = useState(true)");
lines.push("  const router = useRouter()");
lines.push("");
lines.push("  useEffect(() => {");
lines.push("    async function loadUser() {");
lines.push("      const supabase = createClient()");
lines.push("      const { data: { user } } = await supabase.auth.getUser()");
lines.push("      if (!user) { router.push('/auth/login'); return }");
lines.push("      setEmail(user.email || '')");
lines.push("      const date = new Date(user.created_at)");
lines.push("      setCreatedAt(date.toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' }))");
lines.push("      setLoading(false)");
lines.push("    }");
lines.push("    loadUser()");
lines.push("  }, [])");
lines.push("");
lines.push("  async function handleSignOut() {");
lines.push("    const supabase = createClient()");
lines.push("    await supabase.auth.signOut()");
lines.push("    router.push('/auth/login')");
lines.push("  }");
lines.push("");
lines.push("  const g = '#39ff14'");
lines.push("  const dg = '#4dbd4d'");
lines.push("  const mg = '#2d5a2d'");
lines.push("  const cb = '#0d0d0d'");
lines.push("  const bd = '#1a1a1a'");
lines.push("");
lines.push("  if (loading) return <main style={{minHeight:'100vh',background:'#000000',color:dg,display:'flex',alignItems:'center',justifyContent:'center'}}>Loading...</main>");
lines.push("");
lines.push("  return (");
lines.push("    <main style={{minHeight:'100vh',background:'#000000',color:'white',padding:'24px'}}>"); 
lines.push("      <div style={{maxWidth:'480px',margin:'0 auto'}}>"); 
lines.push("        <h1 style={{fontSize:'24px',fontWeight:'bold',marginBottom:'24px',color:g}}>Profile</h1>");
lines.push("        <div style={{background:cb,border:'1px solid '+bd,borderRadius:'8px',padding:'20px',marginBottom:'16px'}}>"); 
lines.push("          <div style={{marginBottom:'16px',paddingBottom:'16px',borderBottom:'1px solid '+bd}}>"); 
lines.push("            <span style={{fontSize:'11px',color:mg,display:'block',marginBottom:'4px',fontWeight:'600'}}>EMAIL</span>"); 
lines.push("            <span style={{fontSize:'15px'}}>{email}</span>"); 
lines.push("          </div>"); 
lines.push("          <div>"); 
lines.push("            <span style={{fontSize:'11px',color:mg,display:'block',marginBottom:'4px',fontWeight:'600'}}>MEMBER SINCE</span>"); 
lines.push("            <span style={{fontSize:'15px'}}>{createdAt}</span>"); 
lines.push("          </div>"); 
lines.push("        </div>"); 
lines.push("        <div style={{background:cb,border:'1px solid '+bd,borderRadius:'8px',padding:'20px',marginBottom:'16px'}}>"); 
lines.push("          <h2 style={{fontSize:'14px',fontWeight:'600',color:dg,marginBottom:'12px'}}>About Protocol</h2>"); 
lines.push("          <p style={{fontSize:'13px',color:mg,lineHeight:'1.6',margin:0}}>Protocol is a personal harm reduction tracking tool. It does not provide medical advice, recommend dosing, or facilitate sourcing of any substances. All data is private to your account.</p>"); 
lines.push("        </div>"); 
lines.push("        <button onClick={handleSignOut} style={{width:'100%',background:'#1a0000',border:'1px solid #4a0000',color:'#ff6b6b',fontWeight:'700',padding:'14px',borderRadius:'6px',fontSize:'16px',cursor:'pointer'}}>"); 
lines.push("          Sign out"); 
lines.push("        </button>"); 
lines.push("      </div>"); 
lines.push("    </main>"); 
lines.push("  )"); 
lines.push("}");
fs.writeFileSync('app/profile/page.tsx', lines.join('\n'), 'utf8');
console.log('Done');
