const fs = require('fs');
const lines = [];
lines.push("'use client'");
lines.push("");
lines.push("import { useState, useEffect } from 'react'");
lines.push("import { createClient } from '../../../../lib/supabase'");
lines.push("import { useRouter } from 'next/navigation'");
lines.push("");
lines.push("const BLOCKED_WORDS = ['source','vendor','buy','purchase','supplier','website','shop','order','link','dm','discord','telegram','whatsapp','price','cost','cheap','discount','promo','code','sale']");
lines.push("");
lines.push("type Post = { id: string; username: string; content: string; tag: string | null; created_at: string }");
lines.push("type Cohort = { id: string; name: string; description: string }");
lines.push("");
lines.push("export default function CohortPage({ params }: { params: { id: string } }) {");
lines.push("  const [cohort, setCohort] = useState<Cohort | null>(null)");
lines.push("  const [posts, setPosts] = useState<Post[]>([])");
lines.push("  const [username, setUsername] = useState('')");
lines.push("  const [content, setContent] = useState('')");
lines.push("  const [tag, setTag] = useState('')");
lines.push("  const [loading, setLoading] = useState(true)");
lines.push("  const [posting, setPosting] = useState(false)");
lines.push("  const [error, setError] = useState('')");
lines.push("  const [userId, setUserId] = useState('')");
lines.push("  const router = useRouter()");
lines.push("  const g = '#39ff14'");
lines.push("  const dg = '#4dbd4d'");
lines.push("  const mg = '#2d5a2d'");
lines.push("  const cb = '#0d0d0d'");
lines.push("  const bd = '#1a1a1a'");
lines.push("");
lines.push("  useEffect(() => { loadData() }, [])");
lines.push("");
lines.push("  async function loadData() {");
lines.push("    setLoading(true)");
lines.push("    const supabase = createClient()");
lines.push("    const { data: { user } } = await supabase.auth.getUser()");
lines.push("    if (!user) { router.push('/auth/login'); return }");
lines.push("    setUserId(user.id)");
lines.push("    const { data: un } = await supabase.from('usernames').select('username').eq('user_id', user.id).single()");
lines.push("    if (un) setUsername(un.username)");
lines.push("    const { data: ch } = await supabase.from('cohorts').select('*').eq('id', params.id).single()");
lines.push("    if (ch) setCohort(ch)");
lines.push("    const { data: p } = await supabase.from('cohort_posts').select('*').eq('cohort_id', params.id).order('created_at', { ascending: false })");
lines.push("    setPosts(p || [])");
lines.push("    setLoading(false)");
lines.push("  }");
lines.push("");
lines.push("  function containsBlockedWord(text: string) {");
lines.push("    const lower = text.toLowerCase()");
lines.push("    return BLOCKED_WORDS.some(word => lower.includes(word))");
lines.push("  }");
lines.push("");
lines.push("  async function submitPost() {");
lines.push("    setError('')");
lines.push("    if (!content.trim()) { setError('Please write something before posting.'); return }");
lines.push("    if (content.trim().length < 10) { setError('Post must be at least 10 characters.'); return }");
lines.push("    if (containsBlockedWord(content)) { setError('Your post contains language that is not allowed in this community. Please remove any references to vendors, sourcing, or purchasing.'); return }");
lines.push("    setPosting(true)");
lines.push("    const supabase = createClient()");
lines.push("    const { error: e } = await supabase.from('cohort_posts').insert({");
lines.push("      user_id: userId,");
lines.push("      cohort_id: params.id,");
lines.push("      username,");
lines.push("      content: content.trim(),");
lines.push("      tag: tag || null,");
lines.push("    })");
lines.push("    if (e) { setError(e.message); setPosting(false); return }");
lines.push("    setContent('')");
lines.push("    setTag('')");
lines.push("    setPosting(false)");
lines.push("    loadData()");
lines.push("  }");
lines.push("");
lines.push("  async function deletePost(id: string) {");
lines.push("    const supabase = createClient()");
lines.push("    await supabase.from('cohort_posts').delete().eq('id', id)");
lines.push("    loadData()");
lines.push("  }");
lines.push("");
lines.push("  function timeAgo(dateStr: string) {");
lines.push("    const diff = Date.now() - new Date(dateStr).getTime()");
lines.push("    const mins = Math.floor(diff / 60000)");
lines.push("    if (mins < 60) return mins + 'm ago'");
lines.push("    const hrs = Math.floor(mins / 60)");
lines.push("    if (hrs < 24) return hrs + 'h ago'");
lines.push("    return Math.floor(hrs / 24) + 'd ago'");
lines.push("  }");
lines.push("");
lines.push("  if (loading) return <main style={{minHeight:'100vh',background:'#000000',color:dg,display:'flex',alignItems:'center',justifyContent:'center'}}>Loading...</main>");
lines.push("");
lines.push("  return (");
lines.push("    <main style={{minHeight:'100vh',background:'#000000',color:'white',padding:'24px'}}>"); 
lines.push("      <div style={{maxWidth:'480px',margin:'0 auto'}}>"); 
lines.push("        <button onClick={() => router.push('/community')} style={{background:'none',border:'none',color:mg,fontSize:'13px',cursor:'pointer',padding:0,marginBottom:'16px'}}>Back to community</button>"); 
lines.push("        <h1 style={{fontSize:'22px',fontWeight:'bold',color:g,marginBottom:'4px'}}>{cohort?.name}</h1>"); 
lines.push("        <p style={{color:dg,fontSize:'13px',marginBottom:'24px'}}>{cohort?.description}</p>"); 
lines.push("        <div style={{background:cb,border:'1px solid '+bd,borderRadius:'8px',padding:'16px',marginBottom:'24px'}}>"); 
lines.push("          <textarea value={content} onChange={e => setContent(e.target.value)} placeholder='Share an observation, experience, or question...' rows={3} style={{width:'100%',background:'#000000',border:'1px solid '+bd,borderRadius:'6px',padding:'10px',color:'white',fontSize:'14px',resize:'none',outline:'none',boxSizing:'border-box',marginBottom:'10px'}} />"); 
lines.push("          <div style={{display:'flex',gap:'8px',marginBottom:'10px'}}>"); 
lines.push("            {['observation','side effect','question','milestone'].map(t => ("); 
lines.push("              <button key={t} onClick={() => setTag(tag===t?'':t)} style={{background:tag===t?'#0a1a0a':'none',border:'1px solid '+(tag===t?mg:bd),color:tag===t?dg:mg,fontSize:'11px',padding:'4px 8px',borderRadius:'4px',cursor:'pointer'}}>{t}</button>"); 
lines.push("            ))}"); 
lines.push("          </div>"); 
lines.push("          {error && <div style={{background:'#1a0000',border:'1px solid #4a0000',borderRadius:'6px',padding:'10px',fontSize:'13px',color:'#ff6b6b',marginBottom:'10px'}}>{error}</div>}"); 
lines.push("          <div style={{display:'flex',justifyContent:'space-between',alignItems:'center'}}>"); 
lines.push("            <span style={{fontSize:'11px',color:mg}}>Posting as @{username}</span>"); 
lines.push("            <button onClick={submitPost} disabled={posting} style={{background:posting?'#1a3d1a':g,color:posting?mg:'#000000',fontWeight:'700',padding:'8px 20px',borderRadius:'6px',border:'none',fontSize:'14px',cursor:posting?'not-allowed':'pointer'}}>{posting?'Posting...':'Post'}</button>"); 
lines.push("          </div>"); 
lines.push("        </div>"); 
lines.push("        <div style={{background:'#0a1a0a',border:'1px solid '+mg,borderRadius:'6px',padding:'10px',marginBottom:'20px'}}>"); 
lines.push("          <p style={{fontSize:'11px',color:mg,margin:0}}>No vendor names, sourcing links, purchasing info, or contact details. Posts violating these rules are automatically blocked.</p>"); 
lines.push("        </div>"); 
lines.push("        {posts.length === 0 && <div style={{textAlign:'center',padding:'48px 0'}}><p style={{color:dg}}>No posts yet.</p><p style={{color:mg,fontSize:'13px'}}>Be the first to share an experience.</p></div>}"); 
lines.push("        {posts.map(post => ("); 
lines.push("          <div key={post.id} style={{background:cb,border:'1px solid '+bd,borderRadius:'8px',padding:'16px',marginBottom:'12px'}}>"); 
lines.push("            <div style={{display:'flex',justifyContent:'space-between',alignItems:'flex-start',marginBottom:'8px'}}>"); 
lines.push("              <div style={{display:'flex',alignItems:'center',gap:'8px'}}>"); 
lines.push("                <span style={{fontSize:'13px',fontWeight:'700',color:dg}}>@{post.username}</span>"); 
lines.push("                {post.tag && <span style={{fontSize:'10px',color:mg,background:'#0a1a0a',padding:'2px 6px',borderRadius:'4px'}}>{post.tag}</span>}"); 
lines.push("              </div>"); 
lines.push("              <div style={{display:'flex',alignItems:'center',gap:'8px'}}>"); 
lines.push("                <span style={{fontSize:'11px',color:mg}}>{timeAgo(post.created_at)}</span>"); 
lines.push("                {post.username === username && <button onClick={() => deletePost(post.id)} style={{background:'none',border:'none',color:mg,fontSize:'11px',cursor:'pointer'}}>Delete</button>}"); 
lines.push("              </div>"); 
lines.push("            </div>"); 
lines.push("            <p style={{fontSize:'14px',lineHeight:'1.6',margin:0,color:'#e5e5e5'}}>{post.content}</p>"); 
lines.push("          </div>"); 
lines.push("        ))}"); 
lines.push("      </div>"); 
lines.push("    </main>"); 
lines.push("  )"); 
lines.push("}");
fs.writeFileSync('app/community/cohorts/[id]/page.tsx', lines.join('\n'), 'utf8');
console.log('Done');
