const fs = require('fs');
const content = [
"const CACHE_NAME = 'protocol-v1'",
"",
"const STATIC_ASSETS = [",
"  '/',",
"  '/calculator',",
"  '/protocol',",
"  '/journal',",
"  '/learn',",
"  '/manifest.json',",
"]",
"",
"self.addEventListener('install', (event) => {",
"  event.waitUntil(",
"    caches.open(CACHE_NAME).then((cache) => {",
"      return cache.addAll(STATIC_ASSETS)",
"    })",
"  )",
"  self.skipWaiting()",
"})",
"",
"self.addEventListener('activate', (event) => {",
"  event.waitUntil(",
"    caches.keys().then((cacheNames) => {",
"      return Promise.all(",
"        cacheNames",
"          .filter((name) => name !== CACHE_NAME)",
"          .map((name) => caches.delete(name))",
"      )",
"    })",
"  )",
"  self.clients.claim()",
"})",
"",
"self.addEventListener('fetch', (event) => {",
"  const { request } = event",
"  const url = new URL(request.url)",
"",
"  // Skip non-GET requests and Supabase API calls",
"  if (request.method !== 'GET') return",
"  if (url.hostname.includes('supabase.co')) return",
"",
"  event.respondWith(",
"    caches.match(request).then((cached) => {",
"      if (cached) return cached",
"      return fetch(request).then((response) => {",
"        if (!response || response.status !== 200) return response",
"        const copy = response.clone()",
"        caches.open(CACHE_NAME).then((cache) => {",
"          cache.put(request, copy)",
"        })",
"        return response",
"      }).catch(() => {",
"        return caches.match('/')",
"      })",
"    })",
"  )",
"})",
].join('\n');
fs.writeFileSync('public/sw.js', content, 'utf8');
console.log('Done');
