const fs = require('fs');
const lines = [];
lines.push("'use client'");
lines.push("");
lines.push("import { useState } from 'react'");
lines.push("");
lines.push("const DOSE_PRESETS = [0.1, 0.25, 0.5, 1, 2, 2.5, 5, 7.5, 10]");
lines.push("const STRENGTH_PRESETS = [1, 2, 5, 10, 15, 20]");
lines.push("const WATER_PRESETS = [0.5, 1.0, 1.5, 2.0, 2.5, 3.0]");
lines.push("");
lines.push("function SyringeVisual({ units }: { units: number }) {");
lines.push("  const maxUnits = 100");
lines.push("  const fillPct = Math.min(units / maxUnits, 1)");
lines.push("  const bodyH = 180");
lines.push("  const fillH = bodyH * fillPct");
lines.push("  const fillY = 20 + (bodyH - fillH)");
lines.push("  return (");
lines.push("    <div style={{display:'flex',flexDirection:'column',alignItems:'center',gap:'8px'}}>"); 
lines.push("      <svg width='60' height='240' viewBox='0 0 60 240'>");
lines.push("        {/* Needle */}");
lines.push("        <polygon points='28,220 32,220 30,238' fill='#8b8ba7' />");
lines.push("        {/* Syringe body */}");
lines.push("        <rect x='16' y='20' width='28' height='200' rx='4' fill='#12121a' stroke='#1e1e2e' strokeWidth='2'/>");
lines.push("        {/* Fill level */}");
lines.push("        {fillH > 0 && <rect x='18' y={fillY} width='24' height={fillH} rx='2' fill='#39ff14' opacity='0.7'/>}");
lines.push("        {/* Tick marks */}");
lines.push("        {[0,25,50,75,100].map(tick => {");
lines.push("          const y = 20 + bodyH * (1 - tick/100)");
lines.push("          return <g key={tick}>");
lines.push("            <line x1='44' y1={y} x2='50' y2={y} stroke='#3d3d5c' strokeWidth='1'/>");
lines.push("            <text x='52' y={y+4} fontSize='7' fill='#3d3d5c'>{tick}</text>");
lines.push("          </g>");
lines.push("        })}");
lines.push("        {/* Plunger */}");
lines.push("        <rect x='14' y='16' width='32' height='8' rx='2' fill='#1e1e2e' stroke='#3d3d5c' strokeWidth='1'/>");
lines.push("        <rect x='26' y='8' width='8' height='12' rx='2' fill='#3d3d5c'/>");
lines.push("      </svg>");
lines.push("      {units > 0 && <span style={{fontSize:'11px',color:'#8b8ba7'}}>U-100 syringe</span>}");
lines.push("    </div>");
lines.push("  )");
lines.push("}");
lines.push("");
lines.push("export default function ReconstitutionCalculator() {");
lines.push("  const [dose, setDose] = useState<number|null>(null)");
lines.push("  const [strength, setStrength] = useState<number|null>(null)");
lines.push("  const [water, setWater] = useState<number|null>(null)");
lines.push("  const [customDose, setCustomDose] = useState('')");
lines.push("  const [customStrength, setCustomStrength] = useState('')");
lines.push("  const [customWater, setCustomWater] = useState('')");
lines.push("  const [showCustomDose, setShowCustomDose] = useState(false)");
lines.push("  const [showCustomStrength, setShowCustomStrength] = useState(false)");
lines.push("  const [showCustomWater, setShowCustomWater] = useState(false)");
lines.push("");
lines.push("  const activeDose = showCustomDose ? parseFloat(customDose) : dose");
lines.push("  const activeStrength = showCustomStrength ? parseFloat(customStrength) : strength");
lines.push("  const activeWater = showCustomWater ? parseFloat(customWater) : water");
lines.push("");
lines.push("  const hasAll = activeDose && activeStrength && activeWater && !isNaN(activeDose) && !isNaN(activeStrength) && !isNaN(activeWater)");
lines.push("");
lines.push("  let concentration = 0, volumeMl = 0, syringeUnits = 0, totalMcg = 0");
lines.push("  if (hasAll) {");
lines.push("    totalMcg = activeStrength! * 1000");
lines.push("    concentration = totalMcg / activeWater!");
lines.push("    volumeMl = (activeDose! * 1000) / concentration");
lines.push("    syringeUnits = volumeMl * 100");
lines.push("  }");
lines.push("");
lines.push("  const g = '#39ff14'");
lines.push("  const dg = '#8b8ba7'");
lines.push("  const mg = '#3d3d5c'");
lines.push("  const cb = '#12121a'");
lines.push("  const bd = '#1e1e2e'");
lines.push("");
lines.push("  function PresetBtn({ value, active, onClick, label }: { value: number; active: boolean; onClick: () => void; label?: string }) {");
lines.push("    return (");
lines.push("      <button onClick={onClick} style={{padding:'8px 12px',borderRadius:'8px',border:'1px solid '+(active?g:bd),background:active?'rgba(57,255,20,0.1)':cb,color:active?g:dg,fontSize:'13px',fontWeight:active?'700':'400',cursor:'pointer',transition:'all 0.15s'}}>");
lines.push("        {label || value}");
lines.push("      </button>");
lines.push("    )");
lines.push("  }");
lines.push("");
lines.push("  return (");
lines.push("    <main style={{minHeight:'100vh',background:'#0a0a0f',color:'white',padding:'24px'}}>"); 
lines.push("      <div style={{maxWidth:'520px',margin:'0 auto'}}>"); 
lines.push("        <a href='/' style={{fontSize:'13px',color:mg,textDecoration:'none',display:'block',marginBottom:'24px'}}>← Back</a>");
lines.push("        <h1 style={{fontSize:'26px',fontWeight:'900',marginBottom:'4px',color:g,letterSpacing:'-0.5px'}}>Pep Calculator</h1>");
lines.push("        <p style={{color:dg,fontSize:'13px',marginBottom:'28px'}}>Select your parameters below. Not medical advice.</p>");
lines.push("");
lines.push("        {/* Dose section */}");
lines.push("        <div style={{background:cb,border:'1px solid '+bd,borderRadius:'12px',padding:'20px',marginBottom:'12px'}}>"); 
lines.push("          <h2 style={{fontSize:'13px',fontWeight:'700',color:dg,letterSpacing:'1px',marginBottom:'14px'}}>DOSE OF PEPTIDE (mg)</h2>"); 
lines.push("          <div style={{display:'flex',flexWrap:'wrap',gap:'8px',marginBottom:'12px'}}>"); 
lines.push("            {DOSE_PRESETS.map(v => ("); 
lines.push("              <PresetBtn key={v} value={v} active={!showCustomDose && dose===v} onClick={() => { setDose(v); setShowCustomDose(false) }} />"); 
lines.push("            ))}"); 
lines.push("          </div>"); 
lines.push("          <button onClick={() => setShowCustomDose(!showCustomDose)} style={{fontSize:'12px',color:mg,background:'none',border:'none',cursor:'pointer',padding:0,textDecoration:'underline'}}>"); 
lines.push("            {showCustomDose ? 'Use presets' : 'Enter custom value'}"); 
lines.push("          </button>"); 
lines.push("          {showCustomDose && ("); 
lines.push("            <input type='number' value={customDose} onChange={e => setCustomDose(e.target.value)} placeholder='e.g. 0.3' style={{marginTop:'10px',width:'100%',background:'#0a0a0f',border:'1px solid '+bd,borderRadius:'8px',padding:'10px',color:'white',fontSize:'14px',boxSizing:'border-box',outline:'none'}} />"); 
lines.push("          )}"); 
lines.push("        </div>"); 
lines.push("");
lines.push("        {/* Strength section */}");
lines.push("        <div style={{background:cb,border:'1px solid '+bd,borderRadius:'12px',padding:'20px',marginBottom:'12px'}}>"); 
lines.push("          <h2 style={{fontSize:'13px',fontWeight:'700',color:dg,letterSpacing:'1px',marginBottom:'14px'}}>VIAL STRENGTH (mg)</h2>"); 
lines.push("          <div style={{display:'flex',flexWrap:'wrap',gap:'8px',marginBottom:'12px'}}>"); 
lines.push("            {STRENGTH_PRESETS.map(v => ("); 
lines.push("              <PresetBtn key={v} value={v} active={!showCustomStrength && strength===v} onClick={() => { setStrength(v); setShowCustomStrength(false) }} />"); 
lines.push("            ))}"); 
lines.push("          </div>"); 
lines.push("          <button onClick={() => setShowCustomStrength(!showCustomStrength)} style={{fontSize:'12px',color:mg,background:'none',border:'none',cursor:'pointer',padding:0,textDecoration:'underline'}}>"); 
lines.push("            {showCustomStrength ? 'Use presets' : 'Enter custom value'}"); 
lines.push("          </button>"); 
lines.push("          {showCustomStrength && ("); 
lines.push("            <input type='number' value={customStrength} onChange={e => setCustomStrength(e.target.value)} placeholder='e.g. 7' style={{marginTop:'10px',width:'100%',background:'#0a0a0f',border:'1px solid '+bd,borderRadius:'8px',padding:'10px',color:'white',fontSize:'14px',boxSizing:'border-box',outline:'none'}} />"); 
lines.push("          )}"); 
lines.push("        </div>"); 
lines.push("");
lines.push("        {/* Water section */}");
lines.push("        <div style={{background:cb,border:'1px solid '+bd,borderRadius:'12px',padding:'20px',marginBottom:'24px'}}>"); 
lines.push("          <h2 style={{fontSize:'13px',fontWeight:'700',color:dg,letterSpacing:'1px',marginBottom:'14px'}}>BACTERIOSTATIC WATER (mL)</h2>"); 
lines.push("          <div style={{display:'flex',flexWrap:'wrap',gap:'8px',marginBottom:'12px'}}>"); 
lines.push("            {WATER_PRESETS.map(v => ("); 
lines.push("              <PresetBtn key={v} value={v} active={!showCustomWater && water===v} onClick={() => { setWater(v); setShowCustomWater(false) }} />"); 
lines.push("            ))}"); 
lines.push("          </div>"); 
lines.push("          <button onClick={() => setShowCustomWater(!showCustomWater)} style={{fontSize:'12px',color:mg,background:'none',border:'none',cursor:'pointer',padding:0,textDecoration:'underline'}}>"); 
lines.push("            {showCustomWater ? 'Use presets' : 'Enter custom value'}"); 
lines.push("          </button>"); 
lines.push("          {showCustomWater && ("); 
lines.push("            <input type='number' value={customWater} onChange={e => setCustomWater(e.target.value)} placeholder='e.g. 1.2' style={{marginTop:'10px',width:'100%',background:'#0a0a0f',border:'1px solid '+bd,borderRadius:'8px',padding:'10px',color:'white',fontSize:'14px',boxSizing:'border-box',outline:'none'}} />"); 
lines.push("          )}"); 
lines.push("        </div>"); 
lines.push("");
lines.push("        {/* Results */}");
lines.push("        <div style={{background:cb,border:'1px solid '+(hasAll?g:bd),borderRadius:'12px',padding:'24px',transition:'border-color 0.3s'}}>"); 
lines.push("          <h2 style={{fontSize:'13px',fontWeight:'700',color:dg,letterSpacing:'1px',marginBottom:'20px'}}>RESULTS</h2>"); 
lines.push("          <div style={{display:'flex',gap:'24px',alignItems:'flex-start'}}>"); 
lines.push("            <SyringeVisual units={hasAll ? syringeUnits : 0} />"); 
lines.push("            <div style={{flex:1,display:'flex',flexDirection:'column',gap:'14px'}}>"); 
lines.push("              <div style={{background:'#0a0a0f',borderRadius:'8px',padding:'12px'}}>"); 
lines.push("                <span style={{fontSize:'11px',color:mg,display:'block',marginBottom:'4px',letterSpacing:'1px'}}>PEPTIDE DOSE</span>"); 
lines.push("                <span style={{fontSize:'16px',fontWeight:'700',color:hasAll?'white':mg}}>{hasAll ? activeDose+'mg ('+(activeDose!*1000)+'mcg)' : 'Select dose'}</span>"); 
lines.push("              </div>"); 
lines.push("              <div style={{background:'#0a0a0f',borderRadius:'8px',padding:'12px',border:'1px solid '+(hasAll?mg:bd)}}>"); 
lines.push("                <span style={{fontSize:'11px',color:mg,display:'block',marginBottom:'4px',letterSpacing:'1px'}}>DRAW SYRINGE TO</span>"); 
lines.push("                <span style={{fontSize:'24px',fontWeight:'900',color:hasAll?g:mg}}>{hasAll ? syringeUnits.toFixed(1)+' units' : '—'}</span>"); 
lines.push("                {hasAll && <span style={{fontSize:'12px',color:dg,display:'block',marginTop:'2px'}}>{volumeMl.toFixed(3)} mL</span>}"); 
lines.push("              </div>"); 
lines.push("              <div style={{background:'#0a0a0f',borderRadius:'8px',padding:'12px'}}>"); 
lines.push("                <span style={{fontSize:'11px',color:mg,display:'block',marginBottom:'4px',letterSpacing:'1px'}}>VIAL CONTAINS</span>"); 
lines.push("                <span style={{fontSize:'14px',fontWeight:'600',color:hasAll?'white':mg}}>{hasAll ? (activeStrength!*1000)+'mcg total' : 'Select values'}</span>"); 
lines.push("              </div>"); 
lines.push("              <div style={{background:'#0a0a0f',borderRadius:'8px',padding:'12px'}}>"); 
lines.push("                <span style={{fontSize:'11px',color:mg,display:'block',marginBottom:'4px',letterSpacing:'1px'}}>CONCENTRATION</span>"); 
lines.push("                <span style={{fontSize:'14px',fontWeight:'600',color:hasAll?'white':mg}}>{hasAll ? concentration.toFixed(0)+'mcg/mL' : 'Select values'}</span>"); 
lines.push("              </div>"); 
lines.push("            </div>"); 
lines.push("          </div>"); 
lines.push("          <p style={{fontSize:'11px',color:mg,marginTop:'16px',lineHeight:'1.5'}}>For U-100 insulin syringes only. Reference tool. Not medical advice — verify all calculations independently.</p>"); 
lines.push("        </div>"); 
lines.push("");
lines.push("      </div>"); 
lines.push("    </main>"); 
lines.push("  )"); 
lines.push("}");
fs.writeFileSync('app/calculator/page.tsx', lines.join('\n'), 'utf8');
console.log('Done');
