// Local-only browser QA: actual Health page, charts, styles, navigation and data
// loaders; Supabase transport is mocked. No real account or health data is used.
/* eslint-disable @typescript-eslint/no-require-imports, @typescript-eslint/no-unused-expressions */
const fs=require('node:fs'),path=require('node:path'),os=require('node:os'),cp=require('node:child_process'),http=require('node:http')
const ts=require('typescript'),WebSocket=require('next/dist/compiled/ws'),assert=require('node:assert/strict')
const root=process.cwd(),dir=fs.mkdtempSync(path.join(os.tmpdir(),'mpp016-browser-'))
let chrome;const deadline=setTimeout(()=>{chrome?.kill();console.error('Browser QA timed out');process.exit(1)},120000)
const entry=path.join(dir,'fixture.tsx')
fs.writeFileSync(entry,`import React from ${JSON.stringify(path.join(root,'node_modules/react'))};
import {createRoot} from ${JSON.stringify(path.join(root,'node_modules/react-dom/client'))};
import Report from ${JSON.stringify(path.join(root,'components/health/DoctorReport.tsx'))};
import Health from ${JSON.stringify(path.join(root,'components/health/HealthDashboard.tsx'))};
import BottomTabBar from ${JSON.stringify(path.join(root,'components/app/BottomTabBar.tsx'))};
window.qaMode='full';window.qaUnit='lbs';window.qaWrites=0;window.qaNow='2026-09-24';
window.qaJournal=Array.from({length:120},(_,i)=>{const day=new Date('2026-09-24T12:00:00');day.setDate(day.getDate()-i);return {id:'j'+i,date:day.getFullYear()+'-'+String(day.getMonth()+1).padStart(2,'0')+'-'+String(day.getDate()).padStart(2,'0'),weight:180+i*.12+(i%3)*.2,mood:2+i%4,energy:1+i%5,sleep:6+i%4*.5,hunger:3,notes:null}});
window.qaEvents=[2,14,60,110].map((days,i)=>({id:'e'+i,date:window.qaJournal[days].date,event_type:i%2?'completed':'reactivated',description:null,protocol_id:'p'+i,compound_id:i===0?'c0':null,protocols:{id:'p'+i,name:'Fictional plan '+i,start_date:'2026-01-01',status:'active',compounds:[]},compounds:i===0?{id:'c0',name:'Fictional compound'}:null}));
function Fixture(){const [version,setVersion]=React.useState(0),[key,setKey]=React.useState(0);React.useEffect(()=>{window.qaNavigate=url=>{history.pushState(null,'',url);setVersion(v=>v+1)};window.qaReset=(mode,unit='lbs')=>{window.qaMode=mode;window.qaUnit=unit;history.replaceState(null,'','/health');setKey(k=>k+1)};window.qaRouter={replace:window.qaNavigate,push:window.qaNavigate,refresh:()=>{}}},[]);return <div className="mobile-app-shell" data-version={version}>{location.pathname==='/health/report'?<Report/>:<Health key={key}/>}<BottomTabBar/></div>}
window.qaRouter={replace:()=>{},push:()=>{},refresh:()=>{}};createRoot(document.getElementById('root')).render(<Fixture/>);`)
require.extensions['.ts']=()=>{};require.extensions['.tsx']=()=>{}
const modules=[],ids=new Map(),styles=[]
function bundle(file){file=require.resolve(file);if(ids.has(file))return ids.get(file);const id=modules.length;ids.set(file,id);modules.push(null);let code=fs.readFileSync(file,'utf8')
 if(file===path.join(root,'lib/supabase.ts'))code=`exports.createClient=()=>({auth:{getUser:async()=>({data:{user:{id:'qa-owner'}},error:null})},from:table=>{let from=0,to=499;const query={select(){return this},eq(){return this},order(){return this},limit(){return this},range(a,b){from=a;to=b;return this},returns(){return this},single(){return this},maybeSingle(){return this},then(resolve,reject){return new Promise(r=>setTimeout(r,window.qaMode==='loading'?3000:80)).then(()=>{if(window.qaMode==='error'&&table==='journal_entries')return {data:null,error:{message:'private provider details'}};let rows=table==='journal_entries'?window.qaJournal:table==='protocol_events'?window.qaEvents:[];const mode=window.qaMode;if(mode==='empty'||mode==='nojournal'&&table==='journal_entries'||mode==='noevents'&&table==='protocol_events')rows=[];if(table==='journal_entries'&&mode==='partial')rows=rows.slice(0,5).map((r,i)=>({...r,mood:i%2?r.mood:null,energy:null,sleep:i%2?null:r.sleep,weight:null}));if(table==='journal_entries'&&mode==='sparse')rows=[0,1,2,10,20,30,40,50,80].map((offset,i)=>({...rows[offset],mood:i===0?4:3,energy:i<4?4:3,sleep:7}));if(table==='journal_entries'&&mode==='four')rows=[0,1,3,6].map(offset=>rows[offset]);if(table==='journal_entries'&&mode==='weekly')rows=[0,1,7,8,21,22,28,35,36].map(offset=>rows[offset]);if(table==='journal_entries'&&mode==='weekly-qualified')rows=[0,1,7,8,14,15,21,22].map(offset=>rows[offset]);if(table==='journal_entries'&&mode==='weekly-sparse')rows=[0,1,7,8,21,22].map(offset=>rows[offset]);if(table==='journal_entries'&&mode==='transition')rows=[0,1,2,3,4,10,20,30,80].map(offset=>rows[offset]);if(table==='journal_entries'&&mode==='single')rows=rows.slice(0,1);if(table==='journal_entries'&&mode==='mixed')rows=rows.slice(0,30).map((r,i)=>({...r,energy:i<2?4:null,sleep:null}));if(table==='journal_entries'&&mode==='noweight')rows=rows.map(r=>({...r,weight:null}));if(table==='journal_entries'&&mode==='oneweight')rows=rows.map((r,i)=>({...r,weight:i?null:r.weight}));if(table==='journal_entries'&&mode==='twoweight')rows=rows.map((r,i)=>({...r,weight:i<2?r.weight:null}));return {data:table==='user_profiles'?{weight_unit:window.qaUnit}:rows.slice(from,to+1),error:null}}).then(resolve,reject)}};return query}});`
if(file===path.join(root,'lib/health/useLocalCalendarDate.ts'))code="exports.useLocalCalendarDate=()=>window.qaNow;"
// PDF extraction is an unrelated lazy tool. Keep its native Node fallback out
// of this browser-only harness; this suite does not exercise PDF import.
if(file===require.resolve('pdfjs-dist/legacy/build/pdf.mjs',{paths:[root]}))code="exports.getDocument=()=>{throw Error('PDF import is outside this fixture')};exports.GlobalWorkerOptions={};exports.version='fixture';"
if(file===require.resolve('next/navigation',{paths:[root]}))code="exports.useRouter=()=>window.qaRouter;exports.useSearchParams=()=>new URLSearchParams(location.search);exports.usePathname=()=>location.pathname;"
if(file===require.resolve('next/link',{paths:[root]}))code="const React=require('react');exports.default=({prefetch,...props})=>React.createElement('a',{...props,onClick:e=>{e.preventDefault();window.qaNavigate(props.href)}});exports.__esModule=true;"
if(file.endsWith('.module.css')){const names={},globals=[];let css=code.replace(/:global\(([^)]+)\)/g,(_,value)=>'GLOBALTOKEN'+(globals.push(value)-1));css=css.replace(/\.([a-zA-Z][\w-]*)/g,(_,name)=>'.'+(names[name]='m'+id+'_'+name));css=css.replace(/GLOBALTOKEN(\d+)/g,(_,i)=>globals[i]);styles.push(css);code='module.exports='+JSON.stringify(names)}else if(file.endsWith('.css')){styles.push(code);code='module.exports={}'}
if(/\.(tsx?|m?js)$/.test(file))code=ts.transpileModule(code,{compilerOptions:{module:ts.ModuleKind.CommonJS,jsx:ts.JsxEmit.ReactJSX,target:ts.ScriptTarget.ES2022,esModuleInterop:true}}).outputText
const map={};for(const match of code.matchAll(/require\(["']([^"']+)["']\)/g)){const dep=JSON.parse('"'+match[1]+'"');if(require('node:module').isBuiltin(dep))throw Error('Browser bundle builtin '+dep+' from '+file);map[dep]=bundle(require.resolve(dep,{paths:[path.dirname(file),root]}))}modules[id]=`function(module,exports){const require=name=>load(${JSON.stringify(map)}[name]);${code}\n}`;return id}
const id=bundle(entry),js=`const process={env:{NODE_ENV:'production'}};const modules=[${modules.join(',')}],cache={};function load(id){if(cache[id])return cache[id].exports;const module=cache[id]={exports:{}};modules[id](module,module.exports);return module.exports}load(${id});`
const css=fs.readFileSync(path.join(root,'app/globals.css'),'utf8')+'\n'+fs.readFileSync(path.join(root,'app/mobile-app.css'),'utf8')+'\n'+styles.join('\n')+'\n*{box-sizing:border-box}body{margin:0;font-family:Arial,sans-serif}';
const html=`<!doctype html><html lang="en"><meta name="viewport" content="width=device-width,initial-scale=1"><style>${css}</style><div id="root"></div><script>window.errors=[];window.onerror=(...args)=>window.errors.push(args.slice(0,3));</script><script>${js.replaceAll('</script','<\\/script')}</script></html>`
;(async()=>{const server=http.createServer((_req,res)=>{res.setHeader('Content-Type','text/html; charset=utf-8');res.end(html)});await new Promise(r=>server.listen(0,'127.0.0.1',r));chrome=cp.spawn(process.env.CHROME_PATH||'C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe',['--headless=new','--disable-gpu','--no-first-run','--no-default-browser-check','--remote-debugging-port=0','--user-data-dir='+path.join(dir,'profile'),'about:blank'],{windowsHide:true,stdio:'ignore'});let ws
 try{const portFile=path.join(dir,'profile','DevToolsActivePort');let portText='';for(let i=0;i<100;i++){try{portText=fs.readFileSync(portFile,'utf8');if(portText.includes('/devtools/'))break}catch{}await new Promise(r=>setTimeout(r,100))}if(!portText)throw Error('Chrome failed to start');const targets=await(await fetch('http://127.0.0.1:'+portText.split('\n')[0]+'/json')).json();ws=new WebSocket(targets.find(t=>t.type==='page').webSocketDebuggerUrl);await new Promise((r,j)=>{ws.onopen=r;ws.onerror=j});let seq=0;const pending=new Map();ws.onmessage=e=>{const data=JSON.parse(e.data);if(data.id){const job=pending.get(data.id);pending.delete(data.id);data.error?job.reject(data.error):job.resolve(data.result)}};const cdp=(method,params={})=>new Promise((resolve,reject)=>{const id=++seq;pending.set(id,{resolve,reject});ws.send(JSON.stringify({id,method,params}))});const run=async code=>{const r=await cdp('Runtime.evaluate',{expression:'(async()=>{'+code+'})()',awaitPromise:true,returnByValue:true});if(r.exceptionDetails)throw Error(JSON.stringify(r.exceptionDetails));return r.result.value}
await cdp('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:true});await cdp('Emulation.setFocusEmulationEnabled',{enabled:true});await cdp('Page.navigate',{url:'http://127.0.0.1:'+server.address().port+'/health'});await new Promise(r=>setTimeout(r,1000));
await run(`window.checks=[];window.check=(ok,label)=>{if(!ok)throw Error(label);checks.push(label)};window.tick=()=>new Promise(r=>setTimeout(r,420));window.range=value=>document.querySelector('[aria-label="Health date range"] button:nth-child('+(['7D','30D','90D','All'].indexOf(value)+1)+')');window.reset=async mode=>{qaReset(mode);await tick()};window.weightSection=()=>document.getElementById('health-weight-heading').closest('section');check(errors.length===0,'No initial runtime errors '+JSON.stringify(errors));check(document.querySelector('h1').textContent==='Health','Canonical Health overview');check(range('7D').getAttribute('aria-pressed')==='true','Default range 7D');check(document.querySelectorAll('.app-tab-bar').length===1,'One preserved bottom navigation');`)
 const screenshots=[],measurements=[];const screen=async name=>{const r=await cdp('Page.captureScreenshot',{format:'png',captureBeyondViewport:true});const file=path.join(dir,name+'.png');fs.writeFileSync(file,Buffer.from(r.data,'base64'));screenshots.push(file)}
 const pressKey=async(name,code,virtual,modifiers=0)=>{await cdp('Input.dispatchKeyEvent',{type:'keyDown',key:name,code,windowsVirtualKeyCode:virtual,modifiers});await cdp('Input.dispatchKeyEvent',{type:'keyUp',key:name,code,windowsVirtualKeyCode:virtual,modifiers})}
 if(!process.env.MPP016_BROAD_BROWSER){
  for(const width of [390,1024]){
   await cdp('Emulation.setDeviceMetricsOverride',{width,height:844,deviceScaleFactor:1,mobile:width<600})
   for(const [url,label] of [['/health','Overview'],['/health?view=labs','Labs'],['/health?view=changes','Protocol changes'],['/health?view=analyst','AI Analyst'],['/health/report','Create report']]){
    await run(`qaNavigate('${url}');await tick();const nav=document.querySelector('[aria-label="Health views"]'),button=nav.querySelector('button');nav.scrollLeft=nav.scrollWidth;await tick();const before=document.querySelector('main').getBoundingClientRect().height;button.click();await tick();const menu=document.querySelector('[role=menu]'),bounds=menu.getBoundingClientRect(),anchor=button.getBoundingClientRect(),hrefs=[...menu.querySelectorAll('[role=menuitem]')].map(e=>e.getAttribute('href'));check(button.getAttribute('aria-expanded')==='true'&&button.getAttribute('aria-controls')===menu.id&&menu.getAttribute('aria-labelledby')===button.id,'Menu ARIA ${width} ${label}');check(JSON.stringify(hrefs)===JSON.stringify(['/health?action=add','/health?action=csv','/health?action=pdf']),'Menu destinations ${width} ${label}');check(menu.textContent.includes('Enter a health or lab result.')&&menu.textContent.includes('Upload structured health history.')&&menu.textContent.includes('Upload a lab report.'),'Menu support text ${width} ${label}');check(getComputedStyle(menu).position==='fixed'&&bounds.left>=0&&bounds.right<=innerWidth&&Math.abs(bounds.right-anchor.right)<2,'Menu overlays, anchors, and fits ${width} ${label}');check(Math.abs(document.querySelector('main').getBoundingClientRect().height-before)<1,'No import layout shift ${width} ${label}');document.dispatchEvent(new KeyboardEvent('keydown',{key:'Escape',bubbles:true}));await tick();check(!document.querySelector('[role=menu]')&&document.activeElement===button,'Escape closes and restores focus ${width} ${label}');`)
   }
   await run(`qaNavigate('/health');await tick();let nav=document.querySelector('[aria-label="Health views"]'),button=nav.querySelector('button');nav.scrollLeft=nav.scrollWidth;button.click();await tick();document.querySelector('[role=menuitem][href="/health?action=csv"]').click();await tick();check(location.search==='?action=csv'&&!document.querySelector('[role=menu]'),'Selecting menu action closes and preserves CSV destination ${width}');qaNavigate('/health');await tick();nav=document.querySelector('[aria-label="Health views"]');button=nav.querySelector('button');nav.scrollLeft=nav.scrollWidth;button.click();await tick();document.body.dispatchEvent(new PointerEvent('pointerdown',{bubbles:true}));await tick();check(!document.querySelector('[role=menu]')&&document.activeElement===button,'Outside interaction closes and restores focus ${width}');`)
   await run(`qaNavigate('/health');await tick();const nav=document.querySelector('[aria-label="Health views"]'),button=nav.querySelector('button');nav.scrollLeft=nav.scrollWidth;button.focus();button.click();await tick();check(document.activeElement===document.querySelectorAll('[role=menuitem]')[0],'Opening focuses first menu item ${width}')`)
   await pressKey('Tab','Tab',9)
   await run(`check(!!document.querySelector('[role=menu]')&&document.activeElement===document.querySelectorAll('[role=menuitem]')[1],'Tab within menu keeps it open ${width}');document.querySelectorAll('[role=menuitem]')[2].focus()`)
   await pressKey('Tab','Tab',9)
   await run(`check(!document.querySelector('[role=menu]')&&!document.querySelector('[aria-label="Health views"] button').contains(document.activeElement),'Tab leaving menu closes without trapping focus ${width}');const nav=document.querySelector('[aria-label="Health views"]'),button=nav.querySelector('button');button.focus();button.click();await tick();button.focus()`)
   await pressKey('Tab','Tab',9,8)
   await run(`check(!document.querySelector('[role=menu]')&&document.activeElement.textContent==='Create report','Shift+Tab leaving trigger and menu closes ${width}')`)
   await run(`await reset('weekly');range('All').click();await tick();const fragmented=document.getElementById('health-signals-heading').closest('section');check([...fragmented.querySelectorAll('[data-signal]')].every(e=>e.dataset.state==='sparse'&&!e.querySelector('svg')&&e.textContent.includes('4 of 6 weeks qualify')),'Two-week longest run stays compact ${width}');await reset('weekly-qualified');range('All').click();await tick();const panel=document.getElementById('health-signals-heading').closest('section');check([...panel.querySelectorAll('[data-signal]')].every(e=>e.dataset.state==='trend'&&e.textContent.includes('weekly average')&&e.textContent.includes('Weekly averages from recorded check-ins · 4 of 4 weeks')&&e.querySelectorAll('select option').length===4),'All requirements render weekly averages ${width}');check(!panel.querySelector('.recharts-line-dot'),'No persistent weekly dots ${width}');check([...panel.querySelector('[data-signal=Mood] select').options].every(o=>o.text.includes('observations')),'Weekly exact inspection ${width}');check(document.documentElement.scrollWidth<=innerWidth,'Weekly view fits viewport ${width}');await reset('weekly-sparse');range('All').click();await tick();const sparse=document.getElementById('health-signals-heading').closest('section');check([...sparse.querySelectorAll('[data-signal]')].every(e=>e.dataset.state==='sparse'&&!e.querySelector('svg')&&e.querySelectorAll('select option').length===6),'Under four weeks stays compact ${width}');`)
   await run(`await reset('full');const section=weightSection(),dots=[...section.querySelectorAll('.recharts-line-dot')],curve=section.querySelector('.recharts-line-curve').getBBox();check(section.textContent.includes('7 weigh-ins · Sep 18–Sep 24'),'Weight context uses actual range ${width}');check(Math.abs(+dots[0].getAttribute('cx')-curve.x)<1&&Math.abs(+dots.at(-1).getAttribute('cx')-(curve.x+curve.width))<1,'Weight endpoints fill plot domain ${width}');check(section.querySelectorAll('.recharts-xAxis .recharts-cartesian-axis-tick-value').length<=3,'At most three weight date labels ${width}');await reset('oneweight');const one=weightSection();check(one.textContent.includes('1 weigh-in · Sep 24')&&one.querySelectorAll('.recharts-line-dot').length===1&&(!one.querySelector('.recharts-line-curve')||!one.querySelector('.recharts-line-curve').getAttribute('d')),'One weight is centered marker only ${width}');await reset('twoweight');const two=weightSection(),twoDots=[...two.querySelectorAll('.recharts-line-dot')],twoCurve=two.querySelector('.recharts-line-curve').getBBox();check(two.textContent.includes('2 weigh-ins · Sep 23–Sep 24')&&twoDots.length===2,'Two-weight context ${width}');check(Math.abs(+twoDots[0].getAttribute('cx')-twoCurve.x)<1&&Math.abs(+twoDots[1].getAttribute('cx')-(twoCurve.x+twoCurve.width))<1,'Two weights use plot boundaries ${width}');check(document.documentElement.scrollWidth<=innerWidth,'Weight states fit viewport ${width}');`)
   await screen('visual-correction-'+width)
   measurements.push(await run(`return {width:${width},checks:checks.length,mainWidth:document.querySelector('main').getBoundingClientRect().width}`))
  }
  await run(`check(errors.length===0,'No runtime errors '+JSON.stringify(errors));check(qaWrites===0,'No fixture writes')`)
  const report={checks:await run('return checks'),measurements,screenshots,errors:await run('return errors'),fixture:'Focused actual-component MPP-016 visual correction at 390 and 1024 CSS pixels'};fs.writeFileSync(path.join(os.tmpdir(),'mpp016-browser.json'),JSON.stringify(report,null,2));console.log(JSON.stringify({passed:report.checks.length,measurements,screenshots,report:path.join(os.tmpdir(),'mpp016-browser.json')},null,2));return
 }
for(const width of [390,1024]){await cdp('Emulation.setDeviceMetricsOverride',{width,height:844,deviceScaleFactor:1,mobile:width<600});await run(`await reset('full');`);for(const value of ['7D','30D','90D','All']){measurements.push(await run(`range('${value}').click();await tick();check(document.documentElement.scrollWidth<=innerWidth,'No overflow ${width} ${value}');check(document.querySelector('main').getBoundingClientRect().width<=760,'Desktop constrained width');check(document.querySelectorAll('[aria-label="Key health metrics"] article').length===4,'Four metrics ${width} ${value}');check(document.querySelectorAll('figure[aria-label$="recorded values"] svg').length===4,'Four separate charts ${width} ${value}');const controls=[...document.querySelectorAll('button,a,summary,select')].filter(e=>e.getClientRects().length);check(controls.every(e=>e.getBoundingClientRect().height>=43.9),'44px controls ${width} ${value}');const nav=document.querySelector('.app-tab-bar').getBoundingClientRect();check(nav.bottom<=innerHeight+1,'Bottom nav visible ${width} ${value}');const ticks=weightSection().querySelectorAll('.recharts-xAxis .recharts-cartesian-axis-tick-value');check(ticks.length<=3,'Readable weight tick count ${width} ${value}');return {width:${width},range:'${value}',minControl:Math.min(...controls.map(e=>e.getBoundingClientRect().height)),charts:document.querySelectorAll('figure svg').length,mainWidth:document.querySelector('main').getBoundingClientRect().width};`))}await run(`range('7D').click();await tick();window.scrollTo(0,0)`);await screen('full-'+width)}
await cdp('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:true});
await run(`range('30D').click();await tick();const before=weightSection().textContent;weightSection().querySelector('summary').click();await tick();check(range('30D').getAttribute('aria-pressed')==='true','Inspection preserves range');check(weightSection().querySelector('select').options.length===30,'All weight observations inspectable');check(!!document.querySelector('[aria-label="Health views"] a[href="/health?view=labs"]'),'Labs remains accessible');check(!!document.querySelector('a[href="/health?view=changes"]')&&!!document.querySelector('a[href="/health?view=analyst"]')&&!!document.querySelector('a[href="/health/report"]'),'Changes Analyst Reports remain accessible');qaNavigate('/health?view=labs');await tick();check(document.body.innerText.includes('Recent panels'),'Existing Labs surface remains');qaNavigate('/health');await tick();check(range('30D').getAttribute('aria-pressed')==='true','Range survives Health subview interaction');check(document.getElementById('health-weight-heading').compareDocumentPosition(document.getElementById('health-command-briefing'))&Node.DOCUMENT_POSITION_FOLLOWING,'Protocol events below charts');check(!document.querySelector('.recharts-reference-line'),'No permanent event labels over charts');`)
for(const mode of ['partial','noweight','oneweight','twoweight','nojournal','noevents','empty']){await run(`await reset('${mode}');check(document.documentElement.scrollWidth<=innerWidth,'No overflow ${mode}');check(!!document.querySelector('[aria-label="Health views"]'),'Health tools remain accessible ${mode}');check(!/NaN|Infinity/.test(document.querySelector('main').textContent),'Finite text ${mode}');`);if(mode==='partial')await run(`check(document.querySelector('[data-signal=Energy]').textContent.includes('No recorded data'),'Missing signal has local empty state');check(document.querySelectorAll('figure svg').length===0,'Partial signals below the stricter thresholds stay compact')`);if(mode==='noweight')await run(`check(weightSection().textContent.includes('Record a weight'),'No-weight empty state')`);if(mode==='oneweight')await run(`const section=weightSection(),dots=section.querySelectorAll('.recharts-line-dot'),curve=section.querySelector('.recharts-line-curve');check(section.textContent.includes('1 weigh-in · Sep 24')&&section.textContent.includes('One recorded value'),'Single weight has concise context');check(dots.length===1&&(!curve||!curve.getAttribute('d')),'Single weight is one marker without a trend line')`);if(mode==='twoweight')await run(`const section=weightSection(),dots=[...section.querySelectorAll('.recharts-line-dot')],plot=section.querySelector('.recharts-line-curve').getBBox();check(section.textContent.includes('2 weigh-ins · Sep 23–Sep 24'),'Two-weight context uses actual dates');check(dots.length===2&&Math.abs(+dots[0].getAttribute('cx')-plot.x)<1&&Math.abs(+dots[1].getAttribute('cx')-(plot.x+plot.width))<1,'Two weights occupy plot date boundaries')`);if(mode==='nojournal'||mode==='empty')await run(`check(document.body.innerText.includes('Your overview starts here'),'No-journal summary');check(!document.querySelector('figure svg'),'No fabricated observations')`);if(mode==='noevents'||mode==='empty')await run(`check(!document.querySelector('[data-kind=activity]'),'No fabricated activity briefing')`);if(mode==='partial'||mode==='empty')await screen(mode+'-390')}
await run(`await reset('error');check(document.querySelectorAll('[role=alert]').length===1,'One human-readable error');check(!document.body.innerText.includes('private provider'),'No provider details');check(!!document.querySelector('[aria-label="Health views"]'),'Error preserves Health navigation');qaMode='full';[...document.querySelectorAll('button')].find(b=>b.textContent==='Try again').click();await tick();check(!!document.getElementById('health-glance'),'Retry restores dashboard')`)
// Navigation is shared across actual Health subviews and Report, without a footer duplicate.
for(const width of [390,1024]){
 await cdp('Emulation.setDeviceMetricsOverride',{width,height:844,deviceScaleFactor:1,mobile:width<600});
 for(const [url,label] of [['/health','Overview'],['/health?view=labs','Labs'],['/health?view=changes','Protocol changes'],['/health?view=analyst','AI Analyst'],['/health/report','Create report'],['/health?action=add','Add / Import'],['/health?action=csv','Add / Import'],['/health?action=pdf','Add / Import']]){
  await run(`qaNavigate('${url}');await tick();const nav=document.querySelector('[aria-label="Health views"]');check(document.querySelectorAll('[aria-label="Health views"]').length===1,'One Health navigation ${width} ${label}');check(!!nav.closest('header'),'Health navigation remains in top header ${width} ${label}');check([...nav.children].map(e=>e.textContent).join('|')==='Overview|Labs|Protocol changes|AI Analyst|Create report|Add / Import','Navigation order ${width} ${label}');const active=nav.querySelector('[aria-current=page]'),a=active.getBoundingClientRect(),n=nav.getBoundingClientRect();check(active.textContent==='${label}'&&a.left>=n.left-1&&a.right<=n.right+1,'Active navigation brought into view ${width} ${label}');check([...nav.children].every(e=>e.getBoundingClientRect().height>=44),'Navigation touch targets ${width} ${label}');check(document.documentElement.scrollWidth<=innerWidth,'No navigation page overflow ${width} ${label}');nav.scrollLeft=nav.scrollWidth;await tick();const beforeHeight=document.querySelector('main').getBoundingClientRect().height,button=nav.querySelector('button');button.click();await tick();const menu=document.querySelector('[role=menu]'),m=menu.getBoundingClientRect(),b=button.getBoundingClientRect();check(button.getAttribute('aria-expanded')==='true'&&button.getAttribute('aria-controls')===menu.id,'Menu ARIA ${width} ${label}');check(menu.querySelectorAll('[role=menuitem]').length===3&&menu.textContent.includes('Enter a health or lab result.')&&menu.textContent.includes('Upload structured health history.')&&menu.textContent.includes('Upload a lab report.'),'Menu actions and support ${width} ${label}');check(m.left>=0&&m.right<=innerWidth&&Math.abs(m.right-b.right)<2,'Menu anchored and within viewport ${width} ${label}');check(Math.abs(document.querySelector('main').getBoundingClientRect().height-beforeHeight)<1,'Menu overlays without layout shift ${width} ${label}');document.dispatchEvent(new KeyboardEvent('keydown',{key:'Escape',bubbles:true}));await tick();check(!document.querySelector('[role=menu]')&&document.activeElement===button,'Escape closes and restores focus ${width} ${label}');`);
 }
}
await cdp('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:true});
await run(`qaNavigate('/health');await tick();let nav=document.querySelector('[aria-label="Health views"]'),button=nav.querySelector('button');nav.scrollLeft=nav.scrollWidth;button.click();await tick();document.querySelector('[role=menuitem]').click();await tick();check(location.search==='?action=add'&&!document.querySelector('[role=menu]'),'Menu selection preserves destination and closes');qaNavigate('/health');await tick();nav=document.querySelector('[aria-label="Health views"]');button=nav.querySelector('button');nav.scrollLeft=nav.scrollWidth;button.click();await tick();document.body.dispatchEvent(new PointerEvent('pointerdown',{bubbles:true}));await tick();check(!document.querySelector('[role=menu]')&&document.activeElement===button,'Outside interaction closes and restores focus');await reset('four');check([...document.querySelectorAll('[data-signal]')].every(e=>e.dataset.state==='sparse'&&!e.querySelector('svg')&&e.textContent.includes('4 of 7 days')&&e.querySelectorAll('select option').length===4),'Four of seven days shows exact values and coverage without plots');check(!document.getElementById('health-signals-heading').closest('section').querySelector('.recharts-line-dot'),'No isolated persistent signal markers');const briefing=document.getElementById('health-command-briefing').closest('section');check(briefing.querySelectorAll('li').length<=3&&briefing.querySelector('[data-kind=confidence]'),'Briefing ranks bounded deterministic insights');check(!document.body.innerText.includes('Changes alongside your data'),'Raw Protocol Context feed removed');`);await screen('four-of-seven-390');
await run(`await reset('full');check([...document.querySelectorAll('[data-signal]')].every(e=>e.querySelector('.recharts-line-curve')&&!e.querySelector('.recharts-line-dot')),'Qualified continuous signals draw lines without persistent dots');`)
// Synthetic sparse datasets exercise the real model and rendering together.
for(const width of [390,1024]){
 await cdp('Emulation.setDeviceMetricsOverride',{width,height:844,deviceScaleFactor:1,mobile:true});
 await run(`await reset('sparse');range('90D').click();await tick();window.signalsPanel=()=>document.getElementById('health-signals-heading').closest('section');const panel=signalsPanel();check(panel.textContent.includes('Not enough consistent data for trends'),'Sparse heading ${width}');check(panel.textContent.includes('9 of 90 days include recorded check-ins.'),'Sparse recorded-day scope ${width}');check(panel.querySelectorAll('svg').length===0,'No sparse signal charts ${width}');check(panel.querySelectorAll('summary').length===3&&[...panel.querySelectorAll('select')].every(e=>e.options.length===9),'One exact-value inspector per compact signal ${width}');check([...panel.querySelectorAll('[data-signal]')].every(e=>e.textContent.includes('9 entries')),'Exact sparse entry counts ${width}');check(panel.querySelector('[data-signal=Mood]').textContent.includes('3.1')&&panel.querySelector('[data-signal=Energy]').textContent.includes('3.4')&&panel.querySelector('[data-signal=Sleep]').textContent.includes('7.0'),'Actual sparse averages ${width}');check(!!weightSection().querySelector('svg'),'Intermittent weight remains visible ${width}');check(document.documentElement.scrollWidth<=innerWidth&&[...panel.querySelectorAll('h2,p,a,strong')].every(e=>e.getBoundingClientRect().right<=innerWidth),'Sparse layout fits ${width}');check([...panel.querySelectorAll('summary')].every(e=>e.getBoundingClientRect().height>=44),'Sparse inspection touch targets ${width}');`);
 await screen('sparse-'+width);
}
await run(`range('All').click();await tick();check(signalsPanel().querySelectorAll('svg').length===0,'Sparse All does not draw a continuous trend');await reset('single');check([...document.querySelectorAll('[data-signal]')].every(e=>e.dataset.state==='single'&&e.textContent.includes('1 entry')&&e.querySelector('time')?.dateTime==='2026-09-24'&&!e.querySelector('svg')),'Single values show dates without charts');await reset('mixed');range('30D').click();await tick();check(document.querySelector('[data-signal=Mood]').querySelector('svg')&&!document.querySelector('[data-signal=Energy]').querySelector('svg')&&!document.querySelector('[data-signal=Sleep]').querySelector('svg'),'Mixed states retain only the qualifying chart');check(document.querySelector('[data-signal=Energy]').textContent.includes('2 entries'),'Mixed sparse count');check(document.querySelector('[data-signal=Sleep]').textContent.includes('No recorded data'),'Zero observations copy');await reset('transition');range('90D').click();await tick();range('7D').click();await new Promise(r=>setTimeout(r,50));check(signalsPanel().getAnimations().length===1,'One layout transition between sparse and trend');check([...signalsPanel().querySelectorAll('[data-animate]')].every(e=>e.dataset.animate==='false'),'Newly qualifying trends appear without point animation');await tick();check(signalsPanel().querySelectorAll('svg').length===3,'Qualifying 7D signals visible');range('90D').click();await tick();check(!signalsPanel().querySelector('svg'),'Returning to sparse removes plots');`);
await run(`await reset('weekly');range('All').click();await tick();const fragmented=document.getElementById('health-signals-heading').closest('section');check([...fragmented.querySelectorAll('[data-signal]')].every(e=>e.dataset.state==='sparse'&&!e.querySelector('svg')&&e.textContent.includes('4 of 6 weeks qualify')),'Two-week longest run stays compact');await reset('weekly-qualified');range('All').click();await tick();const panel=document.getElementById('health-signals-heading').closest('section');check([...panel.querySelectorAll('[data-signal]')].every(e=>e.dataset.state==='trend'&&e.textContent.includes('weekly average')&&e.textContent.includes('Weekly averages from recorded check-ins · 4 of 4 weeks')&&e.querySelectorAll('select option').length===4),'All requirements render qualifying Monday weekly averages');check(!panel.querySelector('.recharts-line-dot'),'Weekly trends have no persistent dots');const options=[...panel.querySelector('[data-signal=Mood] select').options];check(options.every(o=>o.text.includes('observations')),'Weekly inspector exposes date range average and observation count');await reset('weekly-sparse');range('All').click();await tick();const sparse=document.getElementById('health-signals-heading').closest('section');check([...sparse.querySelectorAll('[data-signal]')].every(e=>e.dataset.state==='sparse'&&!e.querySelector('svg')&&e.querySelectorAll('select option').length===6),'Fewer than four qualifying weeks stays in compact summary');`)
await cdp('Emulation.setEmulatedMedia',{features:[{name:'prefers-reduced-motion',value:'reduce'}]});await run(`await tick();range('7D').click();await new Promise(r=>setTimeout(r,30));check(signalsPanel().getAnimations().length===0,'Reduced motion disables sparse layout transition');await tick();`);await cdp('Emulation.setEmulatedMedia',{features:[{name:'prefers-reduced-motion',value:'no-preference'}]});
// Real Recharts keyboard/pointer interaction, with text inspection as a touch alternative.
await run(`qaReset('loading');await new Promise(r=>setTimeout(r,150));check(document.body.innerText.includes('Loading your health overview'),'Loading is explicit');check(!document.querySelector('figure svg')&&!document.querySelector('[aria-label="Key health metrics"]'),'Loading never animates fake values');check(!!document.querySelector('[aria-label="Health views"]'),'Loading preserves Health navigation');`)
await run(`await reset('full');weightSection().scrollIntoView({block:'center'});weightSection().querySelector('.recharts-surface').focus();`)
await cdp('Input.dispatchKeyEvent',{type:'keyDown',key:'ArrowRight',code:'ArrowRight',windowsVirtualKeyCode:39});await cdp('Input.dispatchKeyEvent',{type:'keyUp',key:'ArrowRight',code:'ArrowRight',windowsVirtualKeyCode:39});await run(`await tick();check(weightSection().textContent.includes('Weight 180'),'Keyboard exposes named exact weight');check(getComputedStyle(document.activeElement).outlineStyle==='none'&&getComputedStyle(document.activeElement.closest('[data-chart-frame]')).boxShadow!=='none','Chart keyboard focus uses the rounded frame instead of an SVG rectangle')`)
const point=await run(`const e=weightSection().querySelector('.recharts-line-dot');const r=e.getBoundingClientRect();return {x:r.x+r.width/2,y:r.y+r.height/2}`);await cdp('Input.dispatchMouseEvent',{type:'mouseMoved',x:point.x,y:point.y});await run(`await tick();check(weightSection().querySelector('[role=status]')?.textContent.includes('lbs'),'Pointer exposes weight and unit');weightSection().querySelector('summary').click();await tick();check(weightSection().querySelector('select').getBoundingClientRect().height>=44,'Touch-friendly exact-value selector')`)
// Exercise native keyboard navigation, not just programmatic focus.
const key=async(name,code,virtual,modifiers=0)=>{await cdp('Input.dispatchKeyEvent',{type:'keyDown',key:name,code,windowsVirtualKeyCode:virtual,modifiers,text:name==='Enter'?'\r':name===' '?' ':undefined});await cdp('Input.dispatchKeyEvent',{type:'keyUp',key:name,code,windowsVirtualKeyCode:virtual,modifiers})};
await run(`weightSection().querySelector('details').open=false;weightSection().querySelector('summary').focus()`);await key('Tab','Tab',9,8);await run(`check(document.activeElement.matches('.recharts-surface'),'Shift+Tab reaches named chart');check(getComputedStyle(document.activeElement.closest('[data-chart-frame]')).boxShadow!=='none','Keyboard frame indicator visible');`);await key('ArrowLeft','ArrowLeft',37);await key('ArrowRight','ArrowRight',39);await key('Tab','Tab',9);await run(`check(document.activeElement.tagName==='SUMMARY','Tab reaches native inspection');`);await key('Enter','Enter',13);await run(`check(weightSection().querySelector('details').open,'Enter opens value inspection')`);await key(' ','Space',32);await run(`check(!weightSection().querySelector('details').open,'Space closes value inspection')`);
const clickPoint=await run(`weightSection().querySelector('.recharts-surface').scrollIntoView({block:'center'});const r=weightSection().querySelector('.recharts-line-dot').getBoundingClientRect();return {x:r.x+r.width/2,y:r.y+r.height/2}`);
await cdp('Input.dispatchMouseEvent',{type:'mouseMoved',...clickPoint});await cdp('Input.dispatchMouseEvent',{type:'mousePressed',button:'left',clickCount:1,...clickPoint});await cdp('Input.dispatchMouseEvent',{type:'mouseReleased',button:'left',clickCount:1,...clickPoint});await run(`await tick();check(getComputedStyle(weightSection().querySelector('.recharts-surface')).outlineStyle==='none'&&getComputedStyle(weightSection().querySelector('[data-chart-frame]')).boxShadow==='none','Mouse click has no SVG or frame focus rectangle');check(weightSection().querySelector('[role=status]')?.textContent.includes('lbs'),'Mouse click preserves exact-value inspection')`);
await cdp('Emulation.setTouchEmulationEnabled',{enabled:true});await cdp('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[clickPoint]});await cdp('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await run(`await tick();check(getComputedStyle(weightSection().querySelector('.recharts-surface')).outlineStyle==='none'&&getComputedStyle(weightSection().querySelector('[data-chart-frame]')).boxShadow==='none','Touch has no SVG or frame focus rectangle');check(weightSection().querySelector('[role=status]')?.textContent.includes('lbs'),'Touch preserves exact-value inspection');weightSection().querySelector('summary').click();`);await cdp('Emulation.setTouchEmulationEnabled',{enabled:false});
const accessibility=await cdp('Accessibility.getFullAXTree');assert.ok(accessibility.nodes.some(n=>n.name?.value?.startsWith('Weight chart.')));assert.ok(accessibility.nodes.some(n=>n.name?.value==='Weight recorded date and value'));
await run(`check([...document.querySelectorAll('[data-animate]')].every(e=>e.dataset.animate==='false'),'No initial-load chart or summary animation');
const selector='.recharts-line-curve';const paths=()=>[...document.querySelectorAll(selector)].map(e=>e.getAttribute('d')).join('|');
const before=paths();range('30D').click();await new Promise(r=>setTimeout(r,100));const during=paths();await tick();const after=paths();check(before!==during&&during!==after,'Actual chart paths interpolate during range change');
check(document.querySelector('[aria-label="Key health metrics"]').textContent.includes('30/30'),'Range updates metrics');check(document.getElementById('health-glance').parentElement.textContent.includes('Last 30 days'),'Range updates summary');check(document.querySelectorAll('figure')[0].querySelectorAll('select option').length===30,'Range updates weight observations');check(document.querySelectorAll('figure')[1].querySelectorAll('select option').length===30,'Range updates signal observations');check(document.getElementById('health-command-briefing').closest('section').querySelector('[data-kind=activity]').textContent.includes('2 protocol changes'),'Range updates aggregated protocol activity');
const lum=color=>{const rgb=color.match(/[\\d.]+/g).slice(0,3).map(Number).map(x=>{x/=255;return x<=.04045?x/12.92:Math.pow((x+.055)/1.055,2.4)});return .2126*rgb[0]+.7152*rgb[1]+.0722*rgb[2]};
const contrast=(foreground,background)=>{const a=lum(foreground),b=lum(background);return (Math.max(a,b)+.05)/(Math.min(a,b)+.05)};
const cards=[...document.querySelectorAll('[aria-label="Key health metrics"] article')];check(cards.every(card=>[...card.querySelectorAll('h3,p,small')].every(e=>contrast(getComputedStyle(e).color,getComputedStyle(card).backgroundColor)>=4.5)),'Metric values units labels and supporting text exceed 4.5:1');
check(contrast(getComputedStyle(range('30D')).color,getComputedStyle(range('30D')).backgroundColor)>=4.5,'Selected range contrast exceeds 4.5:1');`)
await cdp('Emulation.setEmulatedMedia',{features:[{name:'prefers-reduced-motion',value:'reduce'}]});await run(`await tick();range('90D').click();await tick();check([...document.querySelectorAll('[data-animate]')].every(e=>e.dataset.animate==='false'),'Reduced motion disables all chart and summary motion');`)
await cdp('Emulation.setEmulatedMedia',{features:[{name:'prefers-reduced-motion',value:'no-preference'}]});await run(`await tick();range('7D').click();await tick();check([...document.querySelectorAll('[data-animate]')].every(e=>e.dataset.animate==='true'),'Range enables bounded morph when motion allowed');`)
await run(`const enlarged=[...document.querySelectorAll('main p,main h1,main h2,main h3,main span,main a,main button,main summary,main small,main strong,main label,main select,main output')].map(e=>[e,parseFloat(getComputedStyle(e).fontSize)*2]);enlarged.forEach(([e,size])=>e.style.setProperty('font-size',size+'px','important'));check(enlarged.every(([e,size])=>parseFloat(getComputedStyle(e).fontSize)>=size-.1),'All dashboard text enlarged to 200 percent '+JSON.stringify(enlarged.filter(([e,size])=>parseFloat(getComputedStyle(e).fontSize)<size-.1).map(([e,size])=>({tag:e.tagName,wanted:size,got:getComputedStyle(e).fontSize}))));window.scrollTo(0,0);await tick();check(document.documentElement.scrollWidth<=innerWidth,'Enlarged text no horizontal overflow');check(document.querySelector('.app-tab-bar').getBoundingClientRect().bottom<=innerHeight+1,'Enlarged text keeps nav visible')`);await screen('large-text-390');
await run(`check(errors.length===0,'No runtime errors across flows');check(qaWrites===0,'No fixture writes');`)
const report={checks:await run('return checks'),measurements,screenshots,errors:await run('return errors'),fixture:'Actual HealthDashboard, Command Center, Recharts, CSS, BottomTabBar, and source loader; local mocked Supabase transport'};fs.writeFileSync(path.join(os.tmpdir(),'mpp016-browser.json'),JSON.stringify(report,null,2));console.log(JSON.stringify({passed:report.checks.length,measurements,screenshots,report:path.join(os.tmpdir(),'mpp016-browser.json')},null,2))
}finally{ws?.close();chrome?.kill();server.close();clearTimeout(deadline)}})().catch(error=>{console.error(error);clearTimeout(deadline);process.exitCode=1})
