import assert from 'node:assert/strict'
import {test} from 'node:test'
import {readFileSync} from 'node:fs'
import {createRequire} from 'node:module'
import ts from 'typescript'
const require=createRequire(import.meta.url),cache=new Map()
function load(path){const url=new URL(path,import.meta.url);if(cache.has(url.href))return cache.get(url.href);const out={exports:{}};const code=ts.transpileModule(readFileSync(url,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText;new Function('require','module','exports',code)(name=>name.startsWith('.')?load(new URL(name+'.ts',url).href):require(name),out,out.exports);cache.set(url.href,out.exports);return out.exports}
const {parseCsv,detectColumns,mapCsv,parseReference,parseFlag,parsePdfLines}=load('../lib/health/labImport.ts')
const {draftFromPanel,prepareLabSubmission,duplicateRows}=load('../lib/health/labEditor.ts')
const {prepareLabDraft,biomarkerHistories}=load('../lib/health/labs.ts')
const {normalizeLabTimeline}=load('../lib/health/labTimeline.ts')
const {saveLabPanelV2,deleteLabPanel}=load('../lib/health/loadLabs.ts')
const csv='Test Name,Result,Units,Reference Range,Flag,Test Date\nMarker,12,unit/mL,10-20,N,2026-09-01\nQualitative,Not detected,,,,2026-09-01'
const table=parseCsv(csv),draft=mapCsv(table,detectColumns(table.headers),'example.csv')
test('common CSV aliases auto-map numeric and qualitative values',()=>{assert.equal(draft.results.length,2);const p=prepareLabDraft(draft);assert.equal(p.results[0].value,12);assert.equal(p.results[1].value_text,'Not detected');assert.equal(p.results[1].status,'unknown')})
test('quoted CSV handles BOM, commas, escaped quotes, multiline and CRLF',()=>{const t=parseCsv('\uFEFFTest,Result,Notes\r\n"Marker, A",5,"two\nlines and ""quotes"""\r\n');assert.equal(t.rows[0][0],'Marker, A');assert.equal(t.rows[0][2],'two\nlines and "quotes"')})
test('tab and semicolon exports parse without unit conversion',()=>{for(const delimiter of ['\t',';'])assert.equal(parseCsv(`Test${delimiter}Result\nMarker${delimiter}Negative`).rows[0][1],'Negative')})
test('manual mapping works with nonstandard headers and prohibits duplicate column assignment',()=>{const t=parseCsv('A,B,C\nMarker,4,pg/mL'),m=detectColumns(t.headers);m.biomarker=0;m.value=1;m.unit=2;assert.equal(mapCsv(t,m,'x.csv').results[0].unit,'pg/mL');m.unit=1;assert.throws(()=>mapCsv(t,m,'x.csv'))})
test('optional columns may be absent and uncertain dates stay blank for explicit correction',()=>{const t=parseCsv('Analyte,Value,Date\nMarker,Positive,09/01/2026');const d=mapCsv(t,detectColumns(t.headers),'x.csv');assert.equal(d.test_date,'');assert.equal(d.results[0].entry,'Positive');assert.ok(d.results[0].warnings.some(w=>w.includes('date')))})
test('multiple dates are not silently combined under the first date',()=>{const t=parseCsv('Test,Value,Date\nMarker,1,2026-09-01\nMarker,2,2026-09-02');assert.equal(mapCsv(t,detectColumns(t.headers),'x.csv').test_date,'')})
test('numeric reference bounds are inclusive but strict/comparator and contextual ranges stay text',()=>{assert.equal(parseReference('10–20').reference_low,'10');assert.equal(parseReference('<=20').reference_high,'20');assert.equal(parseReference('<20').reference_high,'');assert.equal(parseReference('Depends on age').reference_text,'Depends on age')})
test('only explicit recognized flags map; Positive is not converted to abnormal',()=>{assert.equal(parseFlag('H').status,'high');assert.equal(parseFlag('A').status,'abnormal');assert.equal(parseFlag('Positive').status,'');assert.ok(parseFlag('Positive').warning)})
test('missing values and mismatched columns get low parse confidence with raw cells preserved',()=>{const t=parseCsv('Test,Value,Unit\nMarker,,mg/L,extra');const d=mapCsv(t,detectColumns(t.headers),'x.csv');assert.equal(d.results[0].import_confidence,'low');assert.deepEqual(d.results[0].source_raw.cells,['Marker','','mg/L','extra'])})
test('unclosed quoted input rejects without silently saving a partial file',()=>{assert.throws(()=>parseCsv('Test,Value\n"Marker,1'))})
test('review is mandatory, excluded rows never enter the payload, corrections preserve raw provenance',()=>{const d=structuredClone(draft);d.results[0].entry='15';d.results[1].included=false;assert.throws(()=>prepareLabSubmission(d,false),/Confirm/);const p=prepareLabSubmission(d,true);assert.equal(p.results.length,1);assert.equal(p.results[0].value,15);assert.equal(p.results[0].source_raw.cells[1],'12');assert.equal(p.results[0].review_confirmed,true)})
test('low-confidence rows can be corrected and explicitly confirmed',()=>{const d=structuredClone(draft);d.results[0].import_confidence='low';assert.equal(prepareLabSubmission(d,true).results[0].import_confidence,'low')})
test('duplicate warnings use exact date/name/value/unit; do not discard or equate other units',()=>{const p=prepareLabDraft(draft);const panels=[{id:'p',test_date:draft.test_date,results:p.results}];assert.equal(duplicateRows(draft,panels).size,2);const changed=structuredClone(draft);changed.results[0].unit='ng/mL';assert.equal(duplicateRows(changed,panels).has(0),false);assert.equal(prepareLabSubmission(draft,true).results.length,2)})
test('duplicates within an imported panel are flagged on both rows',()=>{const d={...draft,results:[draft.results[0],draft.results[0]]};assert.equal(duplicateRows(d,[]).size,2)})
test('numeric spelling differences still flag the same stored value',()=>{const d={...draft,results:[draft.results[0],{...draft.results[0],entry:'12.0'}]};assert.equal(duplicateRows(d,[]).size,2)})
test('V2 save is one owner-authenticated RPC with stable IDs/version and reviewed rows only',async()=>{const calls=[];const client={auth:{getUser:async()=>({data:{user:{id:'owner'}},error:null})},rpc:async(name,args)=>{calls.push({name,args});return {data:'saved',error:null}}};const original={id:'11111111-1111-4111-8111-111111111111',updated_at:'2026-09-01T00:00:00Z'};assert.equal(await saveLabPanelV2(draft,original,true,client),'saved');assert.equal(calls.length,1);assert.equal(calls[0].args.p_panel_id,original.id);assert.equal(calls[0].args.p_expected_updated_at,original.updated_at);assert.ok(!JSON.stringify(calls[0]).includes('user_id'));await assert.rejects(saveLabPanelV2(draft,null,false,client),/Confirm/);assert.equal(calls.length,1)})
test('delete validates IDs, sends expected version, and reports RPC failure without claiming success',async()=>{const calls=[];const client={auth:{getUser:async()=>({data:{user:{id:'owner'}},error:null})},rpc:async(name,args)=>{calls.push({name,args});return {error:null}}};const panel={id:'11111111-1111-4111-8111-111111111111',updated_at:'2026-09-01T00:00:00Z'};await deleteLabPanel(panel,client);assert.equal(calls[0].name,'delete_lab_panel_v2');await assert.rejects(deleteLabPanel({...panel,id:'invalid'},client),/Reload/);await assert.rejects(deleteLabPanel(panel,{...client,rpc:async()=>({error:{message:'denied'}})}),/could not be confirmed/)})
test('editing keeps result IDs and reported status, while derived status is recalculated',()=>{const p=prepareLabDraft(draft);const panel={id:'p',test_date:draft.test_date,panel_name:'Panel',results:p.results.map((r,i)=>({...r,id:`r${i}`}))};const d=draftFromPanel(panel);assert.equal(d.results[0].id,'r0');assert.equal(d.results[0].status,'normal');assert.equal(d.results[1].status,'');assert.equal(prepareLabSubmission(d,false).results[0].id,'r0')})
test('generic PDF parser keeps source lines, flags uncertain rows and accepts qualitative results',()=>{const d=parsePdfLines([{page:1,text:'Example marker 12 unit/mL 10-20 N'},{page:1,text:'Qualitative marker Not detected'}],'x.pdf');assert.equal(d.results[0].entry,'12');assert.equal(d.results[0].status,'normal');assert.equal(d.results[1].entry,'Not detected');assert.equal(d.results[1].import_confidence,'low');assert.equal(d.results[0].source_raw.page,1)})
test('provider adapter failure falls back to generic without brand-specific behavior',()=>{const d=parsePdfLines([{page:1,text:'Arbitrary marker 12 mg/L'}],'x.pdf',[{id:'fixture',matches:()=>true,parse:()=>{throw new Error('unsupported')}}]);assert.equal(d.source_metadata.parser,'generic-pdf-v2');assert.equal(d.results[0].biomarker_name,'Arbitrary marker')})
test('recognized adapter output can extend the parser without altering generic behavior',()=>{const d=parsePdfLines([{page:1,text:'custom layout'}],'x.pdf',[{id:'fixture-layout',matches:()=>true,parse:()=>[draft.results[0]]}]);assert.equal(d.source_metadata.parser,'fixture-layout')})
test('no useful PDF text or no recognized rows gets actionable messaging',()=>{assert.throws(()=>parsePdfLines([],'scan.pdf'),/scanned/);assert.throws(()=>parsePdfLines([{page:1,text:'No table here'}],'x.pdf'),/couldn't detect/)})
test('Timeline follows edited dates and deleted panels naturally; large imported summaries stay compact',()=>{const p=prepareLabDraft(draft);const panel={id:'p',test_date:'2026-09-01',panel_name:'Import',results:Array(100).fill(p.results[0])};assert.ok(normalizeLabTimeline([panel])[0].description.length<100);assert.equal(normalizeLabTimeline([{...panel,test_date:'2026-08-01'}])[0].date,'2026-08-01');assert.deepEqual(normalizeLabTimeline([]),[])})
test('mixed imported units remain separate trend groups',()=>{const p=prepareLabDraft(draft);const histories=biomarkerHistories([{id:'a',test_date:'2026-09-01',results:[{...p.results[0],id:'1'}]},{id:'b',test_date:'2026-09-02',results:[{...p.results[0],unit:'other-unit',id:'2'}]}]);assert.equal(histories[0].units.length,2)})

// Small in-memory PDF fixture with an actual text stream, not mocked extraction.
function pdfFixture(text){const stream=text?`BT /F1 12 Tf 50 700 Td (${text}) Tj ET`:'';const objects=['<< /Type /Catalog /Pages 2 0 R >>','<< /Type /Pages /Kids [3 0 R] /Count 1 >>','<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >>','<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>',`<< /Length ${stream.length} >>\nstream\n${stream}\nendstream`];let s='%PDF-1.4\n';const offsets=[0];objects.forEach((o,i)=>{offsets.push(Buffer.byteLength(s));s+=`${i+1} 0 obj\n${o}\nendobj\n`});const start=Buffer.byteLength(s);s+=`xref\n0 6\n0000000000 65535 f \n${offsets.slice(1).map(n=>String(n).padStart(10,'0')+' 00000 n \n').join('')}trailer\n<< /Size 6 /Root 1 0 R >>\nstartxref\n${start}\n%%EOF`;return new Uint8Array(Buffer.from(s))}
test('real embedded PDF text extraction and textless PDF rejection',async()=>{let code=ts.transpileModule(readFileSync(new URL('../lib/health/pdfImport.ts',import.meta.url),'utf8'),{compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022}}).outputText;code=code.replace('pdfjs-dist/legacy/build/pdf.mjs',new URL('../node_modules/pdfjs-dist/legacy/build/pdf.mjs',import.meta.url).href);const {extractPdfText}=await import('data:text/javascript;base64,'+Buffer.from(code).toString('base64'));const lines=await extractPdfText(pdfFixture('Example marker 12 mg/L'));assert.ok(lines.some(line=>line.text.includes('Example marker 12 mg/L')));await assert.rejects(extractPdfText(pdfFixture('')),/scanned/);await assert.rejects(extractPdfText(new Uint8Array([1,2,3])),/could not be read/)})
