import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { test } from 'node:test'
import ts from 'typescript'

const read = path => readFileSync(new URL(path, import.meta.url), 'utf8')
const migration = read('../supabase/migrations/202609150001_launch_blockers_v1.sql')
const accountRoute = read('../app/api/account/route.ts')
const consentRoute = read('../app/api/ai-consent/route.ts')
const analystRoute = read('../app/api/health-analyst/route.ts')
const reportRoute = read('../app/api/health-report/route.ts')
const pushRoute = read('../app/api/push/route.ts')
const durable = read('../lib/durableRateLimit.ts')
const monitoring = read('../lib/monitoring.ts')
const monitorRoute = read('../app/api/monitor/route.ts')
const consentDialog = read('../components/health/AiConsentDialog.tsx')
const analystUi = read('../components/health/HealthAnalyst.tsx')
const reportUi = read('../components/health/DoctorReport.tsx')
const deletionUi = read('../components/profile/DeleteAccount.tsx')
const settingsUi = read('../components/profile/AiProcessingSettings.tsx')
const privacy = read('../app/privacy/page.tsx')
const profile = read('../app/profile/page.tsx')
const errorPage = read('../app/error.tsx')
const globalError = read('../app/global-error.tsx')
const allRuntime = [accountRoute,consentRoute,analystRoute,reportRoute,pushRoute,durable,monitoring,monitorRoute,consentDialog,analystUi,reportUi,deletionUi,settingsUi,errorPage,globalError].join('\n')

async function loadPure(path) {
  const output = ts.transpileModule(read(path), { compilerOptions: { module: ts.ModuleKind.ESNext, target: ts.ScriptTarget.ES2022 } }).outputText
  return import(`data:text/javascript;base64,${Buffer.from(output).toString('base64')}`)
}

test('account deletion route authenticates with a verified Supabase user',()=>assert.match(accountRoute,/auth\.getUser\(\)/))
test('account deletion requires the exact deliberate confirmation',()=>assert.match(accountRoute,/confirmation !== 'DELETE'/))
test('account deletion mutation requires a same-origin request',()=>assert.match(accountRoute,/isSameOriginRequest/))
test('account deletion checks server-only service configuration before data deletion',()=>assert.ok(accountRoute.indexOf('SUPABASE_SERVICE_ROLE_KEY') < accountRoute.indexOf("rpc('delete_my_account_data_v1'")))
test('owner data transaction occurs before Auth account removal',()=>assert.ok(accountRoute.indexOf("rpc('delete_my_account_data_v1'") < accountRoute.indexOf('auth.admin.deleteUser')))
test('Auth deletion is confined to the server route',()=>{assert.match(accountRoute,/auth\.admin\.deleteUser/);assert.doesNotMatch(deletionUi,/auth\.admin|SUPABASE_SERVICE_ROLE_KEY/)})
test('partial Auth deletion failure never reports success',()=>{assert.match(accountRoute,/partial: true/);assert.match(accountRoute,/status: 500/)})
test('successful deletion invalidates the local session and redirects signed out',()=>{assert.match(deletionUi,/signOut\(\{ scope: 'local' \}\)/);assert.match(deletionUi,/location\.replace\('\/'\)/)})
test('successful deletion clears app-local storage and caches',()=>{for(const value of ['localStorage.clear','sessionStorage.clear','caches.keys'])assert.ok(deletionUi.includes(value))})
test('transactional deletion enumerates every known user-owned table',()=>{for(const table of ['protocols','compounds','phases','protocol_events','injection_logs','journal_entries','lab_panels','lab_results','shared_protocols','push_subscriptions','user_profiles'])assert.ok(migration.includes(`'${table}'`),table)})
test('deletion preflight rejects unaccounted owner tables before its delete loop',()=>assert.ok(migration.indexOf('Account deletion needs review') < migration.indexOf('FOREACH table_name')))
test('deletion function is owner scoped and not callable by anonymous users',()=>{assert.match(migration,/uid uuid:=auth\.uid\(\)/);assert.match(migration,/delete_my_account_data_v1[\s\S]*FROM PUBLIC,anon/)})
test('migration contains no historical UPDATE or backfill statement',()=>{const withoutFunctions=migration.slice(0,migration.indexOf('CREATE OR REPLACE FUNCTION'));assert.doesNotMatch(withoutFunctions,/\bUPDATE\b/i);assert.doesNotMatch(migration,/\bbackfill\b(?!ed)/i)})
test('consent storage is additive and defaults to no transmission',()=>{assert.match(migration,/ADD COLUMN IF NOT EXISTS ai_processing_consent boolean NOT NULL DEFAULT false/);assert.match(migration,/ai_processing_consented_at timestamptz/)})
test('consent version is stored for future disclosure changes',()=>{assert.match(migration,/ai_processing_consent_version smallint/);assert.match(consentRoute,/AI_CONSENT_VERSION/)})
test('analyst route rejects absent consent before loading evidence',()=>assert.ok(analystRoute.indexOf('hasCurrentAiConsent') < analystRoute.indexOf('loadHealthAnalystContext')))
test('Doctor Report enforces consent only for AI summaries',()=>assert.match(reportRoute,/includeAi && !await hasCurrentAiConsent/))
test('deterministic Doctor Report remains available without AI consent',()=>assert.match(reportRoute,/includeAi \? 'health-report-ai' : 'health-report-deterministic'/))
test('first analyst AI use opens the explicit consent surface',()=>{assert.match(analystUi,/AI_CONSENT_REQUIRED/);assert.match(analystUi,/setConsentOpen\(true\)/)})
test('first report AI use opens the same explicit consent surface',()=>{assert.match(reportUi,/AI_CONSENT_REQUIRED/);assert.match(reportUi,/setConsentOpen\(true\)/)})
test('consent can be granted and remembered',()=>{assert.match(consentDialog,/consent: true/);assert.match(consentRoute,/ai_processing_consented_at/)})
test('consent can be revoked from Profile',()=>{assert.match(settingsUi,/consent: false/);assert.match(profile,/AiProcessingSettings/)})
test('revocation clears the consent timestamp',()=>assert.match(consentRoute,/ai_processing_consented_at: consent \? new Date\(\)\.toISOString\(\) : null/))
test('AI consent API authenticates and validates a boolean choice',()=>{assert.match(consentRoute,/auth\.getUser\(\)/);assert.match(consentRoute,/typeof body\.consent !== 'boolean'/)})
test('AI consent dialog is modal, labelled and keyboard cancellable',()=>{for(const value of ['role="dialog"','aria-modal="true"','aria-labelledby','Escape'])assert.ok(consentDialog.includes(value))})
test('AI disclosure names OpenAI, scoped evidence, accuracy, and medical limitation',()=>{for(const value of ['OpenAI','scoped to your request','may be inaccurate','professional medical care'])assert.ok(consentDialog.includes(value))})
test('durable rate limiter uses the database RPC rather than memory in production',()=>{assert.match(durable,/checkRemoteRateLimit/);assert.match(durable,/NODE_ENV !== 'production'/)})
test('durable limiter fails closed in production when storage is unavailable',()=>assert.match(durable,/return \{ allowed: false, retryAfter: 60, available: false \}/))
test('local development retains a bounded memory fallback',()=>assert.match(durable,/rateLimit\(`\$\{bucket\}:\$\{userId\}`/))
test('separate protected route buckets are declared in SQL',()=>{for(const bucket of ['health-analyst','health-report-ai','health-report-deterministic','push-subscribe'])assert.ok(migration.includes(`'${bucket}'`))})
test('rate limit records are owner keyed',()=>assert.match(migration,/PRIMARY KEY \(user_id,bucket\)/))
test('429 responses include calm structured retry information',()=>{for(const route of [analystRoute,reportRoute,pushRoute]){assert.match(route,/code: unavailable \? 'RATE_LIMIT_UNAVAILABLE' : 'RATE_LIMITED'/);assert.match(route,/retryAfter: limit\.retryAfter/)}})
test('blocked requests include the standard Retry-After header',()=>{for(const route of [analystRoute,reportRoute,pushRoute])assert.match(route,/rateLimitHeaders\(limit\)/)})
test('push subscription writes use the durable user-scoped limiter',()=>assert.match(pushRoute,/checkDurableRateLimit\(supabase, user\.id, 'push-subscribe'\)/))
test('monitoring schema has only scrubbed operational columns',()=>{assert.match(migration,/CREATE TABLE IF NOT EXISTS public\.app_error_events/);for(const forbidden of ['health_payload','error_message','stack_trace','user_id uuid'])assert.doesNotMatch(migration.slice(migration.indexOf('CREATE TABLE IF NOT EXISTS public.app_error_events'),migration.indexOf('DO $table_preflight$')),new RegExp(forbidden))})
test('monitor endpoint requires auth but never stores the user identity',()=>{assert.match(monitorRoute,/auth\.getUser\(\)/);assert.doesNotMatch(monitorRoute,/user\.id|user_id/)})
test('monitoring failures cannot break application requests',()=>{assert.match(monitoring,/catch \{\s*return false/);assert.match(monitorRoute,/status: 204/)})
test('client and root error boundaries submit sanitized error types',()=>{assert.match(errorPage,/reportClientError/);assert.match(globalError,/reportClientError/)})
test('server AI and report failures are captured without request bodies',()=>{assert.match(analystRoute,/captureAnalystOperationalError/);assert.match(reportRoute,/captureAnalystOperationalError/);assert.doesNotMatch(monitoring,/question|evidence|dose|lab_value|notes/)})
test('runtime source has no raw console error logging',()=>assert.doesNotMatch(allRuntime,/console\.(error|log|warn)/))
test('privacy page reflects consent, deletion, monitoring, and durable Supabase counters',()=>{for(const value of ['explicitly allow AI processing','revoke AI processing permission','permanently delete your account','Privacy-scrubbed operational events','rate-limit counters'])assert.ok(privacy.includes(value))})
test('destructive confirmation is accessible and mobile sized',()=>{assert.match(deletionUi,/htmlFor="delete-account-confirmation"/);assert.match(deletionUi,/role="alert"/);assert.match(read('../components/profile/ProfileSafety.module.css'),/min-height:44px/)})
test('service-role and AI secrets never appear in client components',()=>assert.doesNotMatch([consentDialog,analystUi,reportUi,deletionUi,settingsUi].join('\n'),/SUPABASE_SERVICE_ROLE_KEY|OPENAI_API_KEY/))
test('migration is wrapped, additive, rerunnable, and protects new tables with RLS',()=>{assert.match(migration,/^--[\s\S]*BEGIN;/);assert.match(migration,/COMMIT;\s*$/);assert.match(migration,/IF NOT EXISTS/);for(const table of ['app_rate_limits','app_error_events'])assert.ok(migration.includes(`ALTER TABLE public.${table} ENABLE ROW LEVEL SECURITY`))})

test('route sanitizer removes query data and dynamic identifiers',async()=>{
  const {sanitizeOperationalRoute}=await loadPure('../lib/monitoringCore.ts')
  assert.equal(sanitizeOperationalRoute('/share/12345678-1234-4234-8234-123456789012?token=health-data'),'/share/:id')
  assert.equal(sanitizeOperationalRoute('/api/health-report?dose=75'),'/api/health-report')
})
test('monitor error types retain only a bounded safe name',async()=>{
  const {sanitizeOperationalType,operationalErrorType}=await loadPure('../lib/monitoringCore.ts')
  assert.equal(operationalErrorType(new TypeError('private health value 75')), 'TypeError')
  assert.equal(sanitizeOperationalType('Provider Error: token=secret'), 'ProviderError:tokensecret')
  assert.ok(sanitizeOperationalType('x'.repeat(200)).length<=80)
})
test('same-origin protection rejects absent, malformed and cross-site origins',async()=>{
  const {isSameOriginRequest}=await loadPure('../lib/requestSecurity.ts')
  const make=origin=>new Request('https://app.example/api/account',{headers:origin?{origin}:{}})
  assert.equal(isSameOriginRequest(make()),false);assert.equal(isSameOriginRequest(make('not a url')),false)
  assert.equal(isSameOriginRequest(make('https://evil.example')),false);assert.equal(isSameOriginRequest(make('https://app.example')),true)
})
test('remote rate decisions are shared across simulated instances and isolated by authenticated user',async()=>{
  const {checkRemoteRateLimit}=await loadPure('../lib/rateLimitCore.ts')
  const store=new Map()
  const client=user=>({rpc:async(_name,{p_bucket})=>{const key=`${user}:${p_bucket}`,count=(store.get(key)||0)+1;store.set(key,count);return{data:[{allowed:count<=2,retry_after_seconds:count<=2?0:30}],error:null}}})
  assert.deepEqual(await checkRemoteRateLimit(client('alice'),'health-analyst'),{allowed:true,retryAfter:0})
  assert.deepEqual(await checkRemoteRateLimit(client('alice'),'health-analyst'),{allowed:true,retryAfter:0})
  assert.deepEqual(await checkRemoteRateLimit(client('alice'),'health-analyst'),{allowed:false,retryAfter:30})
  assert.deepEqual(await checkRemoteRateLimit(client('bob'),'health-analyst'),{allowed:true,retryAfter:0})
  assert.deepEqual(await checkRemoteRateLimit(client('alice'),'health-report-ai'),{allowed:true,retryAfter:0})
})
