// Local-only browser regression: actual components and CSS; every backend call is mocked.
// Run: node tests/protocol-onboarding.browser.cjs (Chrome installed on Windows).
const WebSocket=require('next/dist/compiled/ws');
const fs=require('fs'),path=require('path'),ts=require(path.join(process.cwd(),'node_modules/typescript')),cp=require('child_process'),http=require('http');
let ownedChrome;const deadline=setTimeout(()=>{console.error('Browser QA timed out');ownedChrome?.kill();process.exit(1)},120000);const root=process.cwd(),dir=fs.mkdtempSync(path.join(require('os').tmpdir(),'mpp015-browser-'));
const entry=path.join(dir,'fixture.tsx');
fs.writeFileSync(entry,`import React from ${JSON.stringify(path.join(root,'node_modules/react'))};
import {createRoot} from ${JSON.stringify(path.join(root,'node_modules/react-dom/client'))};
import ManagePage from ${JSON.stringify(path.join(root,'app/protocol/manage/page.tsx'))};
import TodayPage from ${JSON.stringify(path.join(root,'app/protocol/page.tsx'))};
import BottomTabBar from ${JSON.stringify(path.join(root,'components/app/BottomTabBar.tsx'))};
function Fixture(){const [route,setRoute]=React.useState(location.pathname);React.useEffect(()=>{window.qaNavigate=url=>{history.pushState(null,'',url);setRoute(location.pathname)}},[]);return <div className={'mobile-app-shell'+(route==='/protocol'?' today-surface':'')}>{route==='/protocol'?<TodayPage/>:<ManagePage/>}<BottomTabBar/></div>}
createRoot(document.getElementById('root')).render(<Fixture/>);`);
require.extensions['.ts']=()=>{};require.extensions['.tsx']=()=>{};const modules=[],ids=new Map();function bundle(file){file=require.resolve(file);if(ids.has(file))return ids.get(file);const id=modules.length;ids.set(file,id);modules.push(null);let code=fs.readFileSync(file,'utf8');
if(file===path.join(root,'lib/supabase.ts')) code=`exports.createClient=()=>({auth:{getUser:async()=>({data:{user:{id:'qa-owner'}}})},from:table=>{let filters=[],limit=Infinity;const query={select(){return this},eq(k,v){filters.push([k,v]);return this},order(){return this},limit(n){limit=n;return this},single(){return this},then(resolve,reject){let data=table==='protocols'?(window.qaProtocols||[]).filter(p=>filters.every(([k,v])=>k==='user_id'||p[k]===v)).slice(0,limit):table==='user_profiles'?{weight_unit:'lbs'}:[];return Promise.resolve({data,error:null}).then(resolve,reject)}};return query},rpc:async(name,args)=>{if(name!=='save_protocol_with_events_v2')throw Error('Unexpected RPC '+name);(window.qaCalls||=[]).push(args);await new Promise(r=>setTimeout(r,80));if(window.qaFailure==='known')return {error:{code:'P0001',message:'Fixture rejection'},status:400};if(window.qaFailure==='uncertain')throw Error('Fixture lost connection');const id='qa-'+window.qaCalls.length;const protocol={id,created_at:new Date().toISOString(),name:args.p_name,start_date:args.p_start_date,status:args.p_start_date?'active':'planned',compounds:args.p_compounds.map((c,i)=>({...c,id:id+'-c'+i,phases:[{...c.phase,id:id+'-p'+i}]}))};(window.qaProtocols||=[]).unshift(protocol);return {data:id,error:null,status:200}}});`;
if(file===require.resolve('next/navigation',{paths:[root]})) code="exports.useRouter=()=>({push:url=>window.qaNavigate(url),replace:url=>window.qaNavigate(url)});exports.usePathname=()=>location.pathname;";
if(file===require.resolve('next/link',{paths:[root]})) code="const React=require('react');exports.default=({prefetch,onClick,...props})=>React.createElement('a',{...props,onClick:e=>{e.preventDefault();onClick?.(e);window.qaNavigate(props.href)}});exports.__esModule=true;";
if(file.endsWith('.css'))code='module.exports={}';if(/\.(tsx?|m?js)$/.test(file))code=ts.transpileModule(code,{compilerOptions:{module:ts.ModuleKind.CommonJS,jsx:ts.JsxEmit.ReactJSX,target:ts.ScriptTarget.ES2022,esModuleInterop:true}}).outputText;const map={};for(const match of code.matchAll(/require\(["']([^"']+)["']\)/g)){const dep=JSON.parse('"'+match[1]+'"');map[dep]=bundle(require.resolve(dep,{paths:[path.dirname(file),root]}))}modules[id]=`function(module,exports){const require=name=>load(${JSON.stringify(map)}[name]);${code}\n}`;return id}
const id=bundle(entry),js=`const process={env:{NODE_ENV:'production'}};const modules=[${modules.join(',')}],cache={};function load(id){if(cache[id])return cache[id].exports;const module=cache[id]={exports:{}};modules[id](module,module.exports);return module.exports}load(${id});`;
const css=fs.readFileSync(path.join(root,'app/mobile-app.css'),'utf8')+'\n'+fs.readFileSync(path.join(root,'app/protocol/manage/protocols.css'),'utf8')+'\n*{box-sizing:border-box}body{margin:0;font-family:system-ui}';
const html=`<!doctype html><meta name="viewport" content="width=device-width,initial-scale=1"><style>${css}</style><div id="root"></div><script>window.errors=[];window.onerror=(...args)=>window.errors.push(args.slice(0,3));</script><script>${js.replaceAll('</script','<\\/script')}</script>`;
(async()=>{const server=http.createServer((req,res)=>{res.setHeader('Content-Type','text/html; charset=utf-8');res.end(html)});await new Promise(r=>server.listen(0,'127.0.0.1',r));
const chrome=cp.spawn('C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe',['--headless=new','--disable-gpu','--no-first-run','--no-default-browser-check','--remote-debugging-port=0','--user-data-dir='+path.join(dir,'profile'),'about:blank'],{windowsHide:true,stdio:'ignore'});
ownedChrome=chrome;console.log('Chrome launched');try {const portFile=path.join(dir,'profile','DevToolsActivePort');for(let i=0;i<100&&!fs.existsSync(portFile);i++)await new Promise(r=>setTimeout(r,100));if(!fs.existsSync(portFile))throw Error('Chrome did not start');console.log('DevTools available');let portText;for(let i=0;i<30;i++){try{portText=fs.readFileSync(portFile,'utf8');if(portText.includes('/devtools/'))break}catch{}await new Promise(r=>setTimeout(r,100))}const port=portText.split('\n')[0];const targets=await(await fetch('http://127.0.0.1:'+port+'/json')).json();console.log('Target found');const ws=new WebSocket(targets.find(t=>t.type==='page').webSocketDebuggerUrl);await new Promise((r,j)=>{ws.onopen=r;ws.onerror=j});let seq=0;const pending=new Map();ws.onmessage=e=>{const data=JSON.parse(e.data);if(data.id){const job=pending.get(data.id);pending.delete(data.id);data.error?job.reject(data.error):job.resolve(data.result)}};const cdp=(method,params={})=>new Promise((resolve,reject)=>{const id=++seq;pending.set(id,{resolve,reject});ws.send(JSON.stringify({id,method,params}))});const run=async code=>{const r=await cdp('Runtime.evaluate',{expression:'(async()=>{'+code+'})()',awaitPromise:true,returnByValue:true});if(r.exceptionDetails)throw Error(JSON.stringify(r.exceptionDetails));return r.result.value};
console.log('CDP connected');await cdp('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:true});await cdp('Page.navigate',{url:'http://127.0.0.1:'+server.address().port+'/protocol'});await new Promise(r=>setTimeout(r,1000));
const screenshots=[];
const screen=async name=>{const result=await cdp('Page.captureScreenshot',{format:'png',captureBeyondViewport:false});const file=path.join(dir,name+'.png');fs.writeFileSync(file,Buffer.from(result.data,'base64'));screenshots.push(file)};
await run(`window.clickText=(text)=>{const e=[...document.querySelectorAll('button,a,summary')].find(e=>e.textContent.trim()===text);if(!e)throw Error('Missing '+text);e.click()};window.field=label=>document.querySelector('[aria-label="'+label+'"]');window.input=(label,value)=>{const e=field(label);if(!e)throw Error('Missing field '+label);const proto=e.tagName==='SELECT'?HTMLSelectElement.prototype:e.tagName==='TEXTAREA'?HTMLTextAreaElement.prototype:HTMLInputElement.prototype;Object.getOwnPropertyDescriptor(proto,'value').set.call(e,value);e.dispatchEvent(new Event(e.tagName==='SELECT'?'change':'input',{bubbles:true}))};window.tick=()=>new Promise(r=>setTimeout(r,80));window.check=(ok,text)=>{if(!ok)throw Error(text)};window.ringCount=()=>document.querySelectorAll('.protocol-ring-composition .protocol-ring').length;check(!window.errors.length,'Runtime errors '+JSON.stringify(window.errors));check(document.body.innerText.includes('What are you tracking?'),'Empty owner enters step one');check(document.querySelectorAll('[aria-label="Peptides quick picks"] button').length===5,'Five neutral picks');check(getComputedStyle(document.querySelector('.app-tab-bar')).display==='none','Focused navigation hidden');clickText('Not now');await tick();check(location.pathname==='/protocol','Dismissed to Today');check(ringCount()===5,'Dismissed empty five rings');check(getComputedStyle(document.querySelector('.app-tab-bar')).display!=='none','Normal navigation restored');`);
await screen('empty-today-390');
await run(`clickText('Add Protocol');await tick();clickText('Tirzepatide');await tick();clickText('Continue');await tick();check(document.body.innerText.includes('How much do you take?'),'Dose step');clickText('Continue');await tick();check(document.querySelectorAll('[role=alert]').length===1,'One useful missing dose error');input('Medication dose','5');await tick();input('Medication dose unit','mg');await tick();input('How do you take it?','SubQ');await tick();`);
const measurements=[];
for(const width of [320,375,390]) {
  await cdp('Emulation.setDeviceMetricsOverride',{width,height:844,deviceScaleFactor:1,mobile:true});
  measurements.push(await run(`await tick();const main=document.querySelector('.protocols-focused');check(document.documentElement.scrollWidth<=innerWidth,'Page overflow at '+innerWidth);check(main.scrollWidth<=main.clientWidth,'Flow overflow');const action=document.querySelector('.guided-actions').getBoundingClientRect();check(action.bottom<=visualViewport.height+1,'Visible sticky action');const controls=[...document.querySelectorAll('button,input,select,summary')].filter(e=>e.getClientRects().length&&e.getBoundingClientRect().height);check(controls.every(e=>e.getBoundingClientRect().height>=44),'44px control height');return {width:innerWidth,scrollWidth:document.documentElement.scrollWidth,actionBottom:action.bottom,minControlHeight:Math.min(...controls.map(e=>e.getBoundingClientRect().height))};`));
  await screen('dose-'+width);
}
await cdp('Emulation.setDeviceMetricsOverride',{width:390,height:430,deviceScaleFactor:1,mobile:true});
const keyboard=await run(`field('Dose per injection').focus();field('Dose per injection').scrollIntoView({block:'center'});await tick();const box=field('Dose per injection').getBoundingClientRect(),action=document.querySelector('.guided-actions').getBoundingClientRect();check(box.top>=0&&box.bottom<=action.top,'Focused input above primary action in short viewport');check(action.bottom<=visualViewport.height+1,'Action above simulated keyboard');return {inputBottom:box.bottom,actionTop:action.top,actionBottom:action.bottom,height:visualViewport.height};`);
await cdp('Emulation.setDeviceMetricsOverride',{width:320,height:844,deviceScaleFactor:1,mobile:true});
await run(`clickText('Continue');await tick();check(document.body.innerText.includes('When do you inject?'),'Injectable wording');clickText('Custom');await tick();field('Saturday').click();await tick();field('Sunday').click();await tick();clickText('Evening');await tick();check(field('Sunday').getAttribute('aria-pressed')==='true','Sunday selected');clickText('Back');await tick();check(field('Dose per injection').value==='5','Back preserves dose');clickText('Continue');await tick();check(field('Saturday').getAttribute('aria-pressed')==='true','Back preserves days');`);
await screen('schedule-320');
await run(`clickText('Continue');await tick();check(document.body.innerText.includes('When does this protocol begin?'),'Start step');check(!field('How many weeks?'),'No duration default');clickText('Review protocol');await tick();check(document.body.innerText.includes('Does this look right?'),'Review');window.qaFailure='known';clickText('Start tracking');clickText('Start tracking');await tick();await tick();check(window.qaCalls.length===1,'Rapid taps call canonical RPC once');check(document.body.innerText.includes('Your entries are kept'),'Readable save error');check(document.body.innerText.includes('5 mg'),'Review preserves dose');window.qaFailure=null;clickText('Start tracking');await tick();await tick();check(window.qaCalls.length===2,'Safe retry once');check(document.body.innerText.includes('Your protocol is ready'),'First success');check(ringCount()===5,'Success five rings');check(document.querySelectorAll('.protocol-ring-named').length===1,'One named success ring');`);
await screen('first-success-320');
await cdp('Emulation.setEmulatedMedia',{features:[{name:'prefers-reduced-motion',value:'reduce'}]});
await run(`check(getComputedStyle(document.querySelector('.protocol-ring-named')).animationName==='none','Reduced motion suppresses celebration');clickText('Go to Today');await tick();await tick();check(location.pathname==='/protocol','Success goes to Today');check(ringCount()===5,'One active retains five rings');check(document.querySelectorAll('button.protocol-ring-named').length===1,'One accessible named ring');check(document.body.innerText.includes('Tap a named ring to view your protocol.'),'Ring caption');check(!document.body.innerText.includes('What are you tracking?'),'Owned protocol prevents onboarding');`);
await screen('one-active-today-320');
// Existing users use the same shell, without first-user celebration. Planned custom/oral path.
await run(`clickText('Add another protocol');await tick();check(document.body.innerText.includes('Add protocol'),'Existing-user copy');check(!document.body.innerText.includes('Your first protocol'),'No first-user copy');input('Search compounds','Custom oral record');await tick();clickText('Use “Custom oral record”');await tick();clickText('Continue');await tick();input('Medication dose','4');await tick();input('Medication dose unit','mg');await tick();input('How do you take it?','Oral');await tick();check(!document.body.innerText.includes('Does the vial need mixing?'),'No oral vial questions');clickText('Continue');await tick();check(document.body.innerText.includes('When do you take it?'),'Oral wording');clickText('Daily');await tick();clickText('Continue');await tick();clickText('I don’t know yet');await tick();clickText('Review protocol');await tick();clickText('Save protocol');await tick();await tick();check(document.body.innerText.includes('Protocol saved'),'Existing success');check(!document.querySelector('.protocol-ring-success'),'No first-user animation');check(document.body.innerText.includes('Add a start date before Today scheduling begins'),'Planned explanation');check(window.qaCalls.at(-1).p_start_date===null,'Planned canonical dates');clickText('Go to Today');await tick();`);
// Future injection-volume path, without concentration guessing.
await run(`clickText('Add another protocol');await tick();clickText('Tirzepatide');await tick();clickText('Continue');await tick();clickText('I measure my dose another way');await tick();clickText('Injection volume');await tick();input('Injection volume (mL)','0.125');await tick();input('How do you take it?','IM');await tick();clickText('Continue');await tick();clickText('Daily');await tick();clickText('Continue');await tick();clickText('Another date');await tick();input('Protocol start date','2099-01-01');await tick();clickText('Review protocol');await tick();check(document.body.innerText.includes('0.13 mL'),'Presentation rounds volume only');clickText('Start tracking');await tick();await tick();check(document.body.innerText.includes('Scheduled'),'Future remains Scheduled');check(document.body.innerText.includes('Jan 1, 2099'),'Future start explicit');check(document.body.innerText.includes('Next scheduled: Jan 1, 2099'),'Known scheduled occurrence');check(window.qaCalls.at(-1).p_compounds[0].phase.dosing_entry.injection_volume==='0.125','Stored precision unchanged');clickText('Go to Today');await tick();check(document.querySelectorAll('button.protocol-ring-named').length===1,'Planned/Scheduled excluded from active rings');`);
// Ring counts, order and access at each mobile width, including more than five.
const ringResults=[];
for(const width of [320,375,390]) for(const count of [0,1,2,3,4,5,8]) {
  await cdp('Emulation.setDeviceMetricsOverride',{width,height:844,deviceScaleFactor:1,mobile:true});
  ringResults.push(await run(`window.qaNavigate('/protocol/manage');await tick();window.qaProtocols=Array.from({length:${count}},(_,i)=>({id:'p'+i,created_at:'2026-01-'+String(i+1).padStart(2,'0'),name:'Compound '+i,status:'active',start_date:'2026-01-01',compounds:[{id:'c'+i,name:'Compound '+i,phases:[]}]})).reverse();window.qaNavigate('/protocol');await tick();await tick();check(ringCount()===5,'Five ring positions ${count}/${width}');check(document.querySelectorAll('button.protocol-ring-named').length===Math.min(${count},5),'Named count');check(document.documentElement.scrollWidth<=innerWidth,'Ring overflow');if(${count}>5)check(document.body.innerText.includes('+3 more'),'Overflow access');return {width:innerWidth,count:${count},named:document.querySelectorAll('button.protocol-ring-named').length};`));
}
await screen('overflow-today-390');
// Text scaling, keyboard focus and accessibility tree use the actual selected controls.
await run(`clickText('Add another protocol');await tick();document.querySelector('.guided-creation').style.fontSize='200%';check(document.documentElement.scrollWidth<=innerWidth,'Increased text no overflow');`);
await cdp('Input.dispatchKeyEvent',{type:'keyDown',key:'Tab',code:'Tab',windowsVirtualKeyCode:9});await cdp('Input.dispatchKeyEvent',{type:'keyUp',key:'Tab',code:'Tab',windowsVirtualKeyCode:9});
const focus=await run(`const control=document.activeElement.closest('.quick-search-control')||document.activeElement;check(getComputedStyle(control).outlineStyle==='solid','Visible keyboard focus');return {tag:document.activeElement.tagName,name:document.activeElement.getAttribute('aria-label')||document.activeElement.textContent,outline:getComputedStyle(control).outlineStyle};`);
const ax=await cdp('Accessibility.getFullAXTree');
if(!ax.nodes.some(n=>n.name?.value==='Setup progress'))throw Error('Missing accessible progress');
if(!ax.nodes.some(n=>n.name?.value==='What are you tracking?'))throw Error('Missing accessible step heading');
// Search, alternative recording, inline error associations, and actual 200% text sizes.
await run(`input('Search compounds','Thymosin Α1');await tick();clickText('Thymosin Alpha-1');await tick();clickText('Continue');await tick();clickText('I measure my dose another way');await tick();clickText('I’m not sure');await tick();clickText('Continue');await tick();check(document.body.innerText.includes('How much do you take?'),'Unknown amount cannot advance');check(document.querySelector('[aria-describedby="quick-0-method-error"]'),'Method error associated');clickText('Syringe markings');await tick();input('Syringe markings','20');await tick();clickText('Continue');await tick();check(field('Syringe scale').getAttribute('aria-invalid')==='true','Missing scale invalid');input('Syringe scale','40');await tick();input('How do you take it?','Other');await tick();`);
for(const width of [320,375,390]) {
  await cdp('Emulation.setDeviceMetricsOverride',{width,height:844,deviceScaleFactor:1,mobile:true});
  await run(`await tick();check(document.documentElement.scrollWidth<=innerWidth,'Syringe no overflow');`);
}
await run(`clickText('Continue');await tick();check(document.body.innerText.includes('When do you use it?'),'Other route wording');clickText('Daily');await tick();clickText('Continue');await tick();clickText('Set a length');await tick();input('How many weeks?','8');await tick();clickText('Review protocol');await tick();window.qaFailure='uncertain';const before=window.qaCalls.length;clickText('Start tracking');await tick();await tick();check(document.body.innerText.includes('could not confirm'),'Uncertain response explained');check(document.querySelector('.quick-save-primary').disabled,'Uncertain result blocks duplicate retry');check(window.qaCalls.length===before+1,'One uncertain request');window.qaFailure=null;`);
for(const width of [320,375,390]) {
  await cdp('Emulation.setDeviceMetricsOverride',{width,height:844,deviceScaleFactor:1,mobile:true});
  await run(`await tick();check(document.documentElement.scrollWidth<=innerWidth,'Review no overflow');`);
}
await run(`clickText('Back');await tick();for(const e of document.querySelectorAll('.guided-creation h1,.guided-creation label,.guided-creation legend,.guided-creation button,.guided-creation input,.guided-creation select,.quick-selected strong'))e.style.fontSize=(parseFloat(getComputedStyle(e).fontSize)*2)+'px';await tick();check(document.documentElement.scrollWidth<=innerWidth,'200% text no horizontal overflow');`);
await screen('large-text-start-390');
const result={fixture:'Actual Today, ManagePage, Quick Start, success, rings, BottomTabBar and current CSS; local mocked transport, no Supabase requests',measurements,keyboard,ringResults,focus,checks:'ownership entry/dismissal, categories, step validation/back, route wording, weekend schedule, known failure/retry, rapid taps, first success, planned, scheduled, numeric precision, persistent rings, normal navigation, reduced motion, keyboard focus and accessible progress',screenshots,runtimeErrors:await run('return window.errors;')};
fs.writeFileSync(path.join(require('os').tmpdir(),'mpp015-browser.json'),JSON.stringify(result,null,2));console.log(JSON.stringify(result,null,2));
if(result.runtimeErrors.length)throw Error('Browser runtime errors');
await cdp('Browser.close');ws.close();}
finally{clearTimeout(deadline);chrome.kill();server.close();}})().catch(error=>{console.error(error);process.exitCode=1});
