const fs = require('fs');
const lines = [];
lines.push("'use client'");
lines.push("");
lines.push("import { useState, useEffect } from 'react'");
lines.push("import { createClient } from '../../lib/supabase'");
lines.push("");
lines.push("export default function HistoryPage() {");
lines.push("  const [entries, setEntries] = useState<any[]>([])");
lines.push("  const [loading, setLoading] = useState(true)");
lines.push("  const [editingId, setEditingId] = useState<string | null>(null)");
lines.push("  const [mood, setMood] = useState<number | null>(null)");
lines.push("  const [energy, setEnergy] = useState<number | null>(null)");
lines.push("  const [hunger, setHunger] = useState<number | null>(null)");
lines.push("  const [sleep, setSleep] = useState('')");
lines.push("  const [weight, setWeight] = useState('')");
lines.push("  const [notes, setNotes] = useState('')");
lines.push("  const [date, setDate] = useState('')");
lines.push("  const [saving, setSaving] = useState(false)");
lines.push("");
lines.push("  const g = '#39ff14'");
lines.push("  const dg = '#8b8ba7'");
lines.push("  const mg = '#3d3d5c'");
lines.push("  const cb = '#12121a'");
lines.push("  const bd = '#1e1e2e'");
lines.push("");
lines.push("  useEffect(() => { load() }, [])");
lines.push("");
lines.push("  async function load() {");
lines.push("    setLoading(true)");
lines.push("    const supabase = createClient()");
lines.push("    const { data: { user } } = await supabase.auth.getUser()");
lines.push("    if (!user) { setLoading(false); return }");
lines.push("    const { data } = await supabase.from('journal_entries').select('*').order('date', { ascending: false })");
lines.push("    setEntries(data || [])");
lines.push("    setLoading(false)");
lines.push("  }");
lines.push("");
lines.push("  function startEdit(e: any) {");
lines.push("    setEditingId(e.id); setDate(e.date); setMood(e.mood); setEnergy(e.energy)");
lines.push("    setSleep(e.sleep?.toString() || ''); setWeight(e.weight?.toString() || '')");
lines.push("    setHunger(e.hunger ?? null); setNotes(e.notes || '')");
lines.push("    window.scrollTo({ top: 0, behavior: 'smooth' })");
lines.push("  }");
lines.push("");
lines.push("  function cancelEdit() { setEditingId(null) }");
lines.push("");
lines.push("  async function saveEdit() {");
lines.push("    setSaving(true)");
lines.push("    const supabase = createClient()");
lines.push("    const row: any = { mood, energy, notes: notes.trim() }");
lines.push("    if (sleep) row.sleep = parseFloat(sleep)");
lines.push("    if (weight) row.weight = parseFloat(weight)");
lines.push("    if (hunger !== null) row.hunger = hunger");
lines.push("    if (date) row.date = date");
lines.push("    await supabase.from('journal_entries').update(row).eq('id', editingId)");
lines.push("    setSaving(false); setEditingId(null); load()");
lines.push("  }");
lines.push("");
lines.push("  async function deleteEntry(id: string) {");
lines.push("    if (!confirm('Delete this entry?')) return");
lines.push("    const supabase = createClient()");
lines.push("    await supabase.from('journal_entries').delete().eq('id', id)");
lines.push("    load()");
lines.push("  }");
lines.push("");
lines.push("  function ScoreBtn({ value, current, onChange, activeColor = g }: { value: number; current: number | null; onChange: (v: number) => void; activeColor?: string }) {");
lines.push("    const isActive = current === value");
lines.push("    return <button onClick={() => onChange(value)} style={{width:'36px',height:'36px',borderRadius:'50%',border:isActive?'none':'1px solid '+bd,background:isActive?activeColor:cb,color:isActive?'#000':dg,fontSize:'13px',fontWeight:'700',cursor:'pointer'}}>{value}</button>");
lines.push("  }");
lines.push("");
lines.push("  if (loading) return <main style={{minHeight:'100vh',color:dg,display:'flex',alignItems:'center',justifyContent:'center'}}>Loading...</main>");
lines.push("");
lines.push("  return (");
lines.push("    <main style={{minHeight:'100vh',color:'white',padding:'24px'}}>");
lines.push("      <div style={{maxWidth:'540px',margin:'0 auto'}}>");
lines.push("        <h1 style={{fontSize:'24px',fontWeight:'bold',color:g,marginBottom:'4px'}}>History</h1>");
lines.push("        <p style={{color:dg,fontSize:'13px',marginBottom:'20px'}}>Your past entries. Tap Edit to update.</p>");
lines.push("");
lines.push("        {editingId && (");
lines.push("          <div style={{background:cb,border:'1px solid '+bd,borderRadius:'12px',padding:'16px',marginBottom:'16px'}}>");
lines.push("            <h2 style={{fontSize:'13px',fontWeight:'700',color:'#ffffff',letterSpacing:'1px',marginBottom:'14px'}}>EDIT ENTRY</h2>");
lines.push("            <div style={{marginBottom:'10px'}}>");
lines.push("              <span style={{fontSize:'11px',color:mg,display:'block',marginBottom:'4px'}}>Date</span>");
lines.push("              <input type='date' value={date} onChange={e => setDate(e.target.value)} style={{width:'100%',background:'#0a0a0f',border:'1px solid '+bd,borderRadius:'6px',padding:'8px',color:'white',fontSize:'14px',boxSizing:'border-box',colorScheme:'dark'}} />");
lines.push("            </div>");
lines.push("            <div style={{display:'flex',justifyContent:'space-between',alignItems:'center',marginBottom:'10px'}}>");
lines.push("              <span style={{fontSize:'12px',color:dg}}>Mood</span>");
lines.push("              <div style={{display:'flex',gap:'6px'}}>{[1,2,3,4,5].map(v => <ScoreBtn key={v} value={v} current={mood} onChange={setMood} />)}</div>");
lines.push("            </div>");
lines.push("            <div style={{display:'flex',justifyContent:'space-between',alignItems:'center',marginBottom:'10px'}}>");
lines.push("              <span style={{fontSize:'12px',color:dg}}>Energy</span>");
lines.push("              <div style={{display:'flex',gap:'6px'}}>{[1,2,3,4,5].map(v => <ScoreBtn key={v} value={v} current={energy} onChange={setEnergy} activeColor='#f97316' />)}</div>");
lines.push("            </div>");
lines.push("            <div style={{display:'flex',justifyContent:'space-between',alignItems:'center',marginBottom:'10px'}}>");
lines.push("              <span style={{fontSize:'12px',color:dg}}>Hunger</span>");
lines.push("              <div style={{display:'flex',gap:'6px'}}>{[1,2,3,4,5].map(v => <ScoreBtn key={v} value={v} current={hunger} onChange={setHunger} activeColor='#8b5cf6' />)}</div>");
lines.push("            </div>");
lines.push("            <div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:'8px',marginBottom:'10px'}}>");
lines.push("              <div><span style={{fontSize:'11px',color:mg,display:'block',marginBottom:'4px'}}>Sleep</span><input type='number' step='0.5' value={sleep} onChange={e => setSleep(e.target.value)} style={{width:'100%',background:'#0a0a0f',border:'1px solid '+bd,borderRadius:'6px',padding:'8px',color:'white',fontSize:'14px',boxSizing:'border-box'}} /></div>");
lines.push("              <div><span style={{fontSize:'11px',color:mg,display:'block',marginBottom:'4px'}}>Weight</span><input type='number' step='0.1' value={weight} onChange={e => setWeight(e.target.value)} style={{width:'100%',background:'#0a0a0f',border:'1px solid '+bd,borderRadius:'6px',padding:'8px',color:'white',fontSize:'14px',boxSizing:'border-box'}} /></div>");
lines.push("            </div>");
lines.push("            <textarea value={notes} onChange={e => setNotes(e.target.value)} placeholder='Notes...' rows={2} style={{width:'100%',background:'#0a0a0f',border:'1px solid '+bd,borderRadius:'6px',padding:'8px',color:'white',fontSize:'13px',boxSizing:'border-box',resize:'none',marginBottom:'12px'}} />");
lines.push("            <div style={{display:'flex',gap:'8px'}}>");
lines.push("              <button onClick={cancelEdit} style={{flex:1,background:cb,color:dg,border:'1px solid '+bd,borderRadius:'6px',padding:'10px',fontSize:'14px',cursor:'pointer'}}>Cancel</button>");
lines.push("              <button onClick={saveEdit} disabled={saving} style={{flex:2,background:saving?'#1a3d1a':g,color:saving?mg:'#000',border:'none',borderRadius:'6px',padding:'10px',fontSize:'14px',fontWeight:'700',cursor:'pointer'}}>{saving?'Saving...':'Save Changes'}</button>");
lines.push("            </div>");
lines.push("          </div>");
lines.push("        )}");
lines.push("");
lines.push("        {entries.length === 0 && <p style={{color:mg,textAlign:'center',padding:'48px 0'}}>No entries yet. Log your first day from the Dashboard.</p>}");
lines.push("        {entries.map(e => (");
lines.push("          <div key={e.id} style={{background:cb,border:'1px solid '+bd,borderRadius:'8px',padding:'12px',marginBottom:'8px'}}>");
lines.push("            <div style={{display:'flex',justifyContent:'space-between',alignItems:'center',marginBottom:'6px'}}>");
lines.push("              <span style={{fontSize:'13px',fontWeight:'600',color:g}}>{new Date(e.date + 'T12:00:00').toLocaleDateString('en-US',{month:'short',day:'numeric'})}</span>");
lines.push("              <div style={{display:'flex',gap:'10px'}}>");
lines.push("                <button onClick={() => startEdit(e)} style={{background:'none',border:'none',color:dg,cursor:'pointer',fontSize:'12px'}}>Edit</button>");
lines.push("                <button onClick={() => deleteEntry(e.id)} style={{background:'none',border:'none',color:'#ff6b6b',cursor:'pointer',fontSize:'12px'}}>Delete</button>");
lines.push("              </div>");
lines.push("            </div>");
lines.push("            <div style={{display:'flex',gap:'12px',fontSize:'12px',color:dg,flexWrap:'wrap'}}>");
lines.push("              {e.mood !== null && <span>Mood {e.mood}</span>}");
lines.push("              {e.energy !== null && <span>· Energy {e.energy}</span>}");
lines.push("              {e.sleep !== null && <span>· Sleep {e.sleep}h</span>}");
lines.push("              {e.weight && <span>· {e.weight}lbs</span>}");
lines.push("              {e.hunger !== null && e.hunger !== undefined && <span>· Hunger {e.hunger}</span>}");
lines.push("            </div>");
lines.push("            {e.notes && <p style={{fontSize:'12px',color:dg,marginTop:'6px'}}>{e.notes}</p>}");
lines.push("          </div>");
lines.push("        ))}");
lines.push("      </div>");
lines.push("    </main>");
lines.push("  )");
lines.push("}");
fs.writeFileSync('app/journal/page.tsx', lines.join('\n'), 'utf8');
console.log('Done - History page at /journal');
